package providerlock

// instance.go — the same question, asked inside an ADOPTER'S REPO.
//
// ── THE HOLE THIS CLOSES ──────────────────────────────────────────────────────
//
// providerlock.go compares the constraints the template ships against the locks
// the TEMPLATE delivers, in `instance-template/terraform-iac-bootstrap`. That
// catches a half-finished bump before it is released. It cannot see the copy
// that matters most, because of how the two halves travel:
//
//   the CONSTRAINT ships in the ci image (the roots are generated by the llz
//   inside vars.TF_IMAGE and are gitignored — an instance commits zero .tf)
//
//   the PIN ships in the adopter's repo, and `.terraform.lock.hcl` is `owned` in
//   .template-manifest: seeded once at scaffold time and NEVER re-touched by an
//   upgrade
//
// So `llz upgrade` moves the constraint and leaves the pin, by design, and the
// instance's own CI had nothing that looked at the pair. gsap-apl took v0.0.45
// with the linode provider constraint at `~> 4.3` and a lock still pinning
// 3.12.0; repo-readiness passed the upgrade PR clean, and the mismatch first
// appeared in a production apply:
//
//	Error: Failed to resolve provider packages
//	Could not resolve provider linode/linode: locked provider 3.12.0 does not
//	match configured version constraint ~> 4.3
//
// The terraform-init composite recovers that with a single `-upgrade` retry, so
// the run survives — but it survives by re-resolving providers under a plan
// nobody reviewed, on every future run, until someone commits the regenerated
// lock. The retry's own warning says to. Nothing checked that anyone had.
//
// ── WHERE THE CONSTRAINT COMES FROM HERE ──────────────────────────────────────
//
// From the EMBEDDED roots, not from the repo: in an instance there is no
// tools/ tree and no terraform-modules/ to read. That is the right authority —
// the llz running this check is the one whose `llz render` will write the roots,
// and `llz ci assert-image-fresh` is what keeps that binary level with the
// instance's template pin.
//
// ROOT CONSTRAINTS ONLY, and the omission is safe rather than lucky. A root's
// constraint and those of the modules it sources are INTERSECTED, and #507's
// CheckAgreement makes the template refuse to ship a tree where the two
// disagree — so on any released llz the root spec IS the intersection. Reading
// the module half would mean fetching it over the network at gate time, which is
// not a thing a read-repo gate may do.

import (
	"fmt"
	"io"
	"os"
	"path"

	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/capability"
	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/color"
	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/tfroots"
)

// instanceLockDir is where an instance keeps the locks. The template's own copy
// of this tree lives one level down, under instance-template/ — see lockDir.
const instanceLockDir = "terraform-iac-bootstrap"

// ScanInstance compares an instance's committed lockfiles against the provider
// constraints compiled into this binary.
//
// versionsFor is the constraint source, injected so a test can drive the whole
// scan without depending on whatever the embedded roots happen to pin today —
// a fixture that moves every time a dependabot PR lands is a fixture that stops
// asserting anything.
func ScanInstance(repo capability.Repo, versionsFor map[string]string) ([]Result, error) {
	if _, err := repo.ReadDir(instanceLockDir); err != nil {
		return nil, fmt.Errorf("read %s: %w (this is an instance's Terraform tree; "+
			"without it there is nothing to compare and a pass would be a green check over "+
			"a repo this gate did not recognise)", instanceLockDir, err)
	}
	var results []Result
	for root, versions := range versionsFor {
		lockRel := path.Join(instanceLockDir, root, lockFile)
		lockBody, err := repo.ReadFile(lockRel)
		if err != nil {
			if os.IsNotExist(err) {
				continue // this instance committed no lock for this root
			}
			return nil, fmt.Errorf("read %s: %w", lockRel, err)
		}
		locked := ParseLock(string(lockBody))
		if len(locked) == 0 {
			return nil, fmt.Errorf("%s records no provider — either the lock is empty "+
				"(then it should not be committed) or the stanza format changed and this gate is "+
				"reading nothing", lockRel)
		}
		constraints := ParseConstraints(versions, "the "+root+" root shipped in this llz")
		if len(constraints) == 0 {
			return nil, fmt.Errorf("the %s root shipped in this llz declares no provider constraint — "+
				"a root whose lock is committed but whose constraints cannot be read must not pass", root)
		}
		results = append(results, CheckRoot(root, constraints, locked))
	}
	return results, nil
}

// RunInstance scans an instance checkout and reports.
//
// NO COMMITTED LOCK AT ALL IS A PASS, and it is the one place this gate departs
// from fail-closed-on-vacuity. The failure needs a lock to exist: with none,
// `tofu init` resolves providers fresh inside the constraint and cannot be stale.
// The vacuity that WOULD be dangerous — the tree having moved out from under the
// gate — is caught separately by ScanInstance, which requires the directory
// itself to be there.
func RunInstance(repoRoot string, out, errOut io.Writer) error {
	repo := capability.RepoForGate(Extension(), repoRoot)
	results, err := ScanInstance(repo, tfroots.RootVersions())
	if err != nil {
		return err
	}
	compared := 0
	var violations []Violation
	for _, r := range results {
		compared += r.Compared
		violations = append(violations, r.Violations...)
	}
	if len(results) == 0 {
		fmt.Fprintf(out, "provider-lock-guard: this instance commits no %s — nothing can be stale, "+
			"`tofu init` will resolve providers fresh within the shipped constraints.\n", lockFile)
		return nil
	}
	if compared == 0 {
		return fmt.Errorf("provider-lock-guard: found %d committed lock(s) but compared NOTHING — "+
			"no locked provider matched a constrained one. That is a provider-address normalisation "+
			"bug in this gate, not a clean tree", len(results))
	}
	if len(violations) == 0 {
		fmt.Fprintf(out, "provider-lock-guard: OK — %d provider pin(s) across %d root(s) satisfy the "+
			"constraints this llz ships.\n", compared, len(results))
		return nil
	}
	for _, v := range violations {
		fmt.Fprintf(errOut, "::error file=%s/%s/%s::%s is locked at %s and does not satisfy %s\n",
			instanceLockDir, v.Root, lockFile, v.Provider, v.Locked, v.Spec)
	}
	fmt.Fprintf(errOut, "\n%s %d provider pin(s) in this instance cannot satisfy the constraint the "+
		"template it tracks now ships:\n", color.Red("✗"), len(violations))
	for _, v := range violations {
		fmt.Fprintf(errOut, "    %s\n", v)
	}
	fmt.Fprintf(errOut, `
WHY THIS IS NORMAL RIGHT AFTER AN UPGRADE, AND WHY IT STILL HAS TO BE FIXED.
%s is `+"`owned`"+` in .template-manifest: it was seeded when this instance was
scaffolded and `+"`llz upgrade`"+` never touches it again. The constraint it has to
satisfy travels the other way, inside the ci image. So an upgrade that raises a
provider constraint leaves this pair mismatched BY DESIGN, on every instance in
the field, and nothing else in this repo looks at it.

The terraform-init composite does survive it — one `+"`tofu init -upgrade`"+` retry —
but that re-resolves providers on every run, under a plan nobody reviewed, and
its warning has been asking for the regenerated lock to be committed.

TO FIX, per root named above:

    cd %s/<root>
    tofu init -upgrade
    git add %s && git commit

then re-run this check. If you would rather this instance stop carrying a pin
at all, delete the lock: with none committed, `+"`tofu init`"+` resolves fresh inside
the constraint and this gate passes.
`, lockFile, instanceLockDir, lockFile)
	return fmt.Errorf("provider-lock-guard: %d committed provider pin(s) violate the constraint this llz ships", len(violations))
}
