package providerlock

// remedy.go — the instruction an operator gets when the pins their instance
// committed can no longer satisfy the constraints the template ships.
//
// ── WHY -backend=false, WHICH IS THE WHOLE POINT ──────────────────────────────
//
// This remedy said `tofu init -upgrade`, and that command DOES NOT WORK in an
// instance checkout. Every root carries encryption.tf, which holds only the
// enforcement posture, while the key provider and the methods arrive from
// $TF_ENCRYPTION (see ADR 0007 (state encryption)). So an init that configures
// the backend without it stops on OpenTofu's own:
//
//	Error: Invalid expression
//	  on encryption.tf line 69, in terraform:
//	A single static variable reference is required …
//
// which names neither the passphrase nor the variable. The guard that exists to
// unstick an operator was handing them a command that fails, and failing in a way
// that reads as a broken checkout rather than a missing secret. gsap-apl's
// v0.0.46 upgrade PR sat red on exactly this.
//
// -backend=false is not a workaround for the tripwire, it is the correct scope.
// Regenerating a lock is a PROVIDER RESOLUTION, and a provider resolution has no
// business reading state. The flag skips backend initialisation, which is the
// only thing the encryption block is consulted for — so the command needs no
// passphrase, no object-storage credentials and no bucket, and an operator who
// has never run `llz tokens` can still fix their lock.
//
// Measured against OpenTofu 1.12.6 with the shipped encryption.tf and versions.tf:
// `init -upgrade` exits 1 and leaves the lock untouched, `init -backend=false
// -upgrade` exits 0 and rewrites it. TestTheRemedyIsTheCommandThatWorks holds
// both arms against the real embedded roots.
//
// ── ONE STRING, TWO CALLERS ───────────────────────────────────────────────────
//
// `llz ci provider-lock-guard --instance` prints it when the upgrade PR goes red.
// `llz upgrade` prints it at the moment the skew is created, which is hours
// earlier and the same instruction. An operator who ignores the first meets the
// second, so a second copy that drifted would be worse than no second printer.

import (
	"fmt"
	"strings"

	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/color"
)

// RegenerateCmd regenerates one root's lock, and is the load-bearing string here.
//
// -input=false because the operator is reading a remedy, not sitting in a prompt,
// and an init that stops to ask a question in a script looks like a hang.
//
// ── THROUGH `llz tofu`, WHICH IS NOT DECORATION ───────────────────────────────
//
// A bare `tofu` here walked into the trap this remedy's own release documents.
// An instance commits ZERO `.tf` — the roots are generated by `llz render` and
// gitignored — while `.terraform.lock.hcl` IS committed. So a fresh clone has root
// directories holding a lock and nothing else, and `tofu init` in one prints
// "OpenTofu initialized in an empty directory!", EXITS 0, and leaves the stale pin
// exactly where it was. The operator's `git add` stages nothing, they re-run the
// guard, and it fails again with no clue why. That is the case the docs explicitly
// send people to ("run it locally first").
//
// `llz tofu` refuses an unrendered root and names `llz render`. Routing through it
// makes the refusal CONDITIONAL — no unnecessary `llz render` step for the usual
// case where the tree is already rendered, and no silent no-op for the case where
// it is not.
const RegenerateCmd = LlzTofuPrefix + RegenerateTofuArgs

// LlzTofuPrefix is the passthrough marker. `llz tofu` takes OpenTofu's ARGUMENTS
// after `--`, not its binary name, so RegenerateTofuArgs must not carry one —
// composing them with a `tofu` on both sides produced `llz tofu -- tofu init`,
// which passes "tofu" as the subcommand.
const LlzTofuPrefix = "llz tofu -- "

// RegenerateTofuArgs is the OpenTofu half of RegenerateCmd — arguments only, no
// binary. Split out because the gate executes it: what has to be proven is that
// THIS invocation regenerates a lock with no passphrase and no credentials in the
// environment.
const RegenerateTofuArgs = "init -backend=false -upgrade -input=false"

// InstanceLockDir is where an instance keeps its locks, exported so the callers
// that print the remedy do not each spell the path themselves.
const InstanceLockDir = instanceLockDir

// LockFile is the lockfile's name, exported for the same reason.
const LockFile = lockFile

// RegenerateSteps is the remedy as the shell lines that perform it, written for a
// reader who will paste them.
//
// ONE LINE PER ROOT, DEDUPED. A single root can violate on several providers, and
// a remedy that prints the same `cd` three times reads like a bug in the tool
// rather than three findings in one directory. The order is the order the
// violations were reported, so the shell lines and the list above them agree.
func RegenerateSteps(violations []Violation) string {
	var b strings.Builder
	seen := map[string]bool{}
	for _, v := range violations {
		if seen[v.Root] {
			continue
		}
		seen[v.Root] = true
		fmt.Fprintf(&b, "    %s\n", color.Cyan(fmt.Sprintf("(cd %s/%s && %s)", instanceLockDir, v.Root, RegenerateCmd)))
	}
	fmt.Fprintf(&b, "    %s\n", color.Cyan(fmt.Sprintf("git add %s/*/%s && git commit", instanceLockDir, lockFile)))
	return b.String()
}

// Remedy is the full explanation the CI guard prints under the violation list.
//
// It carries the WHY as well as the commands because this failure is the normal
// state of every instance in the field for the first commit after a constraint
// moves, and an operator meeting it for the first time needs to know the tree is
// not broken before they will trust the fix.
func Remedy(violations []Violation) string {
	return fmt.Sprintf(`
WHY THIS IS NORMAL RIGHT AFTER AN UPGRADE, AND WHY IT STILL HAS TO BE FIXED.
%s is `+"`owned`"+` in .template-manifest: it was seeded when this instance was
scaffolded and `+"`llz upgrade`"+` never touches it again. The constraint it has to
satisfy travels the other way, inside the ci image. So an upgrade that raises a
provider constraint leaves this pair mismatched BY DESIGN, on every instance in
the field, and nothing else in this repo looks at it.

The terraform-init composite does survive it — one `+"`tofu init -upgrade`"+` retry —
but that re-resolves providers on every run, under a plan nobody reviewed, and
its warning has been asking for the regenerated lock to be committed.

TO FIX, from the instance root:

%s
then re-run this check.

`+"`-backend=false`"+` IS LOAD-BEARING, not tidiness. Your roots encrypt state at
rest, so an init that configures the backend needs $TF_ENCRYPTION and stops
without it on OpenTofu's own "Invalid expression … A single static variable
reference is required", which names neither the passphrase nor the variable.
Regenerating a lock is a provider resolution and never touches state, so this
form needs no passphrase, no credentials and no bucket. (For the commands that
DO touch state, `+"`llz tofu`"+` resolves that environment for you — see
docs/playbooks/operator-onboarding.md.)

If you would rather this instance stop carrying a pin at all, delete the lock:
with none committed, `+"`tofu init`"+` resolves fresh inside the constraint and this
gate passes.
`, lockFile, RegenerateSteps(violations))
}
