package providerlock

// run.go — the reporting half. Kept out of providerlock.go so the judgement
// there stays a pure function over parsed input, testable with no filesystem.

import (
	"fmt"
	"io"

	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/capability"
	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/color"
)

// Run scans repoRoot and reports. Returns an error when any lock entry violates
// a constraint.
func Run(repoRoot string, out, errOut io.Writer) error {
	results, err := Scan(capability.RepoForGate(Extension(), repoRoot))
	if err != nil {
		return err
	}
	var violations []Violation
	compared := 0
	for _, r := range results {
		compared += r.Compared
		violations = append(violations, r.Violations...)
		for _, n := range r.Notes {
			fmt.Fprintf(out, "  note: %s: %s\n", n.Root, n.Text)
		}
	}
	// FAIL CLOSED ON VACUITY. Locks were found and constraints were found, but if
	// none of them are for the SAME provider then nothing was actually compared —
	// which is what a normalisation bug looks like, and it would otherwise print
	// the same green line as a clean tree.
	if compared == 0 {
		return fmt.Errorf("provider-lock-guard: found locks and constraints but compared NOTHING — " +
			"no locked provider matched a constrained one. That is a provider-address normalisation " +
			"bug in this gate, not a clean tree")
	}
	if len(violations) == 0 {
		fmt.Fprintf(out, "provider-lock-guard: OK — %d provider pin(s) across %d root(s) satisfy the "+
			"constraints the template ships.\n", compared, len(results))
		return nil
	}
	for _, v := range violations {
		fmt.Fprintf(errOut, "::error file=%s/%s/%s::%s is locked at %s and does not satisfy %s\n",
			lockDir, v.Root, lockFile, v.Provider, v.Locked, v.Spec)
	}
	fmt.Fprintf(errOut, "\n%s %d provider pin(s) in a delivered lockfile cannot satisfy the "+
		"constraint the template ships:\n", color.Red("✗"), len(violations))
	for _, v := range violations {
		fmt.Fprintf(errOut, "    %s\n", v)
	}
	fmt.Fprintf(errOut, `
WHY THIS BLOCKS EVERY EXISTING ADOPTER AND NO NEW ONE. The constraint travels in
the ci image (the roots are generated by the llz inside vars.TF_IMAGE and are
gitignored). The pin travels in the adopter's repo — .terraform.lock.hcl is
`+"`owned`"+` in .template-manifest, seeded once at scaffold time and never re-touched
by an upgrade. So a fresh scaffold gets both halves of the bump and every
instance already in the field keeps the old pin. Its next terraform op dies at

    Error: ... locked provider ... does not match configured version constraints

and the terraform-init composite runs a plain `+"`tofu init`"+` with no -upgrade, so
there is no recovery inside CI. release-e2e cannot see this: it force-pushes a
fresh instantiation every run.

TO FIX, do BOTH halves in this PR:
  1. regenerate the lock beside the constraint you moved:
       cd terraform-iac-bootstrap/<root> && tofu init -upgrade
     and commit the resulting %s
  2. decide what existing instances do. A lock they cannot satisfy needs either a
     .template-removals `+"`untrack`"+` entry for it (so the next upgrade stops
     carrying the stale pin) or a release note telling operators to run
     `+"`tofu init -upgrade`"+` once.
`, lockFile)
	return fmt.Errorf("provider-lock-guard: %d delivered provider pin(s) violate a shipped constraint", len(violations))
}
