package upgrade

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/akamai-consulting/lke-landing-zone/tools/internal/extensions/lifecycle/promote"
	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/instancelayout"
)

// The promotion-pipeline REPORT test, the sibling of provider_lock_report_test.go
// and image_skew_report_test.go, and it exists for the reason those do: what
// `llz upgrade` PRINTS is the whole deliverable. It cannot regenerate promote.yml
// (the file is `owned`, and the write lives in internal/cli by declaration), so
// the warning plus its NEXT STEPS line is all an operator gets before
// `llz env pipeline --check` fails the pull request they are about to open.
//
// THE PROPERTY UNDER TEST IS THE STEP, NOT THE PROSE. `llz doctor` already fails
// on this and runs a few lines below — the gap this closes is that its error is
// discarded by design, so the finding never reached the numbered checklist on the
// last screen. A test asserting only that something was printed would pass on the
// release that had the printing and not the step, which is the state this fixes.

// instanceWithStalePipeline seeds the smallest tree that reproduces the real
// case: one declared deployment, and the EMPTY placeholder a pre-v0.0.46 llz
// generated for it. Nothing about that tree is broken — it is stale because the
// generator moved, which is exactly why no diff anywhere reveals it.
func instanceWithStalePipeline(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	mkdirAll(t, filepath.Join(dir, "terraform-iac-bootstrap", "cluster"))
	mkdirAll(t, filepath.Join(dir, ".github", "workflows"))
	write(t, filepath.Join(dir, "terraform-iac-bootstrap", "cluster", "prod.tfvars"),
		"region = \"us-ord\"\n")
	// instance_repo is what resolveCaller falls back to when there is no rendered
	// workflow to copy the pin from.
	write(t, filepath.Join(dir, ".copier-answers.yml"), "instance_repo: akamai/example\n")
	// The `# GENERATED` banner is load-bearing: it is how PlanWorkflow recognises
	// its own output and is willing to replace it. A hand-written promote.yml
	// carrying no banner is left alone, and this reporter must stay silent on it.
	write(t, filepath.Join(dir, ".github", "workflows", "promote.yml"),
		"# GENERATED by `llz env pipeline` — the EMPTY pipeline.\n"+
			"# DO NOT EDIT BY HAND.\n\nname: Promote (no pipeline configured yet)\n\n"+
			"on:\n  workflow_dispatch:\n\njobs:\n"+
			"  llz-preflight:\n    name: Promotion pipeline matches the spec\n"+
			"    runs-on: ubuntu-latest\n    steps:\n"+
			"      - run: llz env pipeline --check --require-pipeline\n")
	return dir
}

func mkdirAll(t *testing.T, dir string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
}

func write(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestAStalePipelineReachesTheChecklist is the gate on the whole change: the
// upgrade must hand printNextSteps a step naming the command that fixes the tree.
func TestAStalePipelineReachesTheChecklist(t *testing.T) {
	chdir(t, instanceWithStalePipeline(t))

	var step string
	_, errOut := captureStdoutStderr(t, func() { step = reportUnrunnablePromotionPipeline() })

	if step == "" {
		t.Fatal("a promote.yml this release regenerates contributed NO next step — " +
			"doctor prints the ✗ and finishUpgrade discards it, so the checklist on the " +
			"last screen is the only place the operator would see this, and it was empty")
	}
	if !strings.Contains(step, "llz env pipeline") {
		t.Errorf("next step = %q, want it to name `llz env pipeline` — a remedy the "+
			"operator has to go look up is the shape this package has shipped five times", step)
	}
	if errOut == "" {
		t.Error("the reporter printed nothing at all — the numbered step is a pointer to " +
			"detail that has to exist above it")
	}
}

// TestAPipelineInSyncIsSilent. The checklist is built from what each reporter
// returned, and a reporter with nothing to say must contribute nothing —
// otherwise the last screen of every upgrade lists a step that does not apply,
// which is how a checklist stops being read.
func TestAPipelineInSyncIsSilent(t *testing.T) {
	dir := instanceWithStalePipeline(t)
	chdir(t, dir)

	// Bring the tree into sync the way an operator would: run the generator's own
	// output back onto disk. Using PlanWorkflow's Content rather than a fixture is
	// deliberate — a hand-written "expected" pipeline would go stale the next time
	// the generator moves, which is the very failure under test.
	syncPipelineFromPlan(t, dir)

	var step string
	_, errOut := captureStdoutStderr(t, func() { step = reportUnrunnablePromotionPipeline() })
	if step != "" || errOut != "" {
		t.Errorf("an in-sync promote.yml produced step %q and output %q, want both empty", step, errOut)
	}
}

// syncPipelineFromPlan writes what the CURRENT generator renders, so this test
// cannot go stale the next time the generator moves.
func syncPipelineFromPlan(t *testing.T, dir string) {
	t.Helper()
	tfDir, _, relPrefix := instancelayout.Detect()
	plan, err := promote.PlanWorkflow(promote.DefaultDeps(), tfDir, relPrefix)
	if err != nil {
		t.Fatal(err)
	}
	if !plan.Changed {
		t.Fatal("the fixture was already in sync — this test would prove nothing")
	}
	write(t, filepath.Join(dir, plan.Path), plan.Content)
}

// TestANonInstanceCheckoutIsSilent. `llz upgrade` in a template-repo checkout has
// no promote.yml to judge — PlanWorkflow returns an empty Path there — and a
// warning about a file that is not present is noise the four reporters around
// this one are all careful not to emit.
func TestANonInstanceCheckoutIsSilent(t *testing.T) {
	dir := t.TempDir()
	mkdirAll(t, filepath.Join(dir, "instance-template", "terraform-iac-bootstrap", "cluster"))
	chdir(t, dir)

	var step string
	_, errOut := captureStdoutStderr(t, func() { step = reportUnrunnablePromotionPipeline() })
	if step != "" || errOut != "" {
		t.Errorf("a template-repo checkout produced step %q and output %q, want both empty", step, errOut)
	}
}
