package main

// custom_layout.go guards the operator escape hatch's directory contract —
// apl-values/_shared/custom/ (clusterspec.CustomRoot).
//
// The tree moved from a FLAT kustomize root (custom/kustomization.yaml listing every
// resource, synced by one `instance-custom` Application) to App Platform's documented
// GitOps layout (https://techdocs.akamai.com/app-platform/docs/gitops):
//
//	custom/namespaces/<ns>/   → one Application per directory, synced into <ns>
//	custom/global/            → cluster-scoped resources
//
// generated by the instance-custom ApplicationSet (clusterspec.RenderInstanceCustom).
//
// WHY THIS IS A HARD GATE, NOT A WARNING. The flat layout's `instance-custom`
// Application carries `resources-finalizer.argocd.argoproj.io`, and the platform-bootstrap
// app-of-apps that syncs the overlay runs `prune: true`. So the moment a render emits an
// ApplicationSet where that Application used to be, platform-bootstrap prunes the
// Application and the finalizer CASCADE-DELETES every workload the operator deployed
// through the hatch. An instance with content in the flat root must therefore move it
// BEFORE the new overlay reaches the cluster — `llz render` refuses until it has, which
// puts the gate ahead of every terraform op (render runs first) rather than trusting an
// operator to have read a release note.
//
// custom/** is `owned` (.template-manifest), so no copier update and no `delete` rule can
// migrate this for the operator: their files are theirs, and a template that deleted them
// would be destroying operator content. Hence a guided, manual migration.

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"

	"github.com/akamai-consulting/lke-landing-zone/tools/internal/clusterspec"
)

// aplReservedPrefix is the directory prefix App Platform reserves for operator-owned
// (apl-operator-written) trees in the values repo — apl-secrets/, apl-users/, and any
// future sibling. The GitOps doc's rule is "do not add, edit, or delete files in any
// apl- prefixed directory"; here the hazard is concrete rather than advisory. A
// namespaces/apl-*/ directory would point an instance-custom Application at a namespace
// apl-core's OWN gitops-ns-apl-* Application already manages, putting two Argo CD
// Applications in contention over the same resources.
const aplReservedPrefix = "apl-"

// flatKustomization is the minimal slice of a kustomization.yaml this guard reads: the
// fields whose presence proves the flat root is CARRYING content rather than sitting as
// the untouched empty starter the template used to ship (`resources: []`).
// sigs.k8s.io/yaml routes through JSON, so these are json tags.
type flatKustomization struct {
	Resources          []string          `json:"resources"`
	Components         []string          `json:"components"`
	Patches            []any             `json:"patches"`
	PatchesStrategic   []any             `json:"patchesStrategicMerge"`
	PatchesJSON6902    []any             `json:"patchesJson6902"`
	HelmCharts         []any             `json:"helmCharts"`
	ConfigMapGenerator []any             `json:"configMapGenerator"`
	SecretGenerator    []any             `json:"secretGenerator"`
	Generators         []string          `json:"generators"`
	Transformers       []string          `json:"transformers"`
	Bases              []string          `json:"bases"`
	CRDs               []string          `json:"crds"`
	NamePrefix         string            `json:"namePrefix"`
	NameSuffix         string            `json:"nameSuffix"`
	Namespace          string            `json:"namespace"`
	CommonLabels       map[string]string `json:"commonLabels"`
	CommonAnnotations  map[string]string `json:"commonAnnotations"`
}

// carriesContent reports whether the flat kustomization declares anything at all beyond
// apiVersion/kind. Any non-zero field means an operator put something here, so the
// migration is destructive and must be gated.
func (k flatKustomization) carriesContent() bool {
	return len(k.Resources) > 0 || len(k.Components) > 0 || len(k.Patches) > 0 ||
		len(k.PatchesStrategic) > 0 || len(k.PatchesJSON6902) > 0 || len(k.HelmCharts) > 0 ||
		len(k.ConfigMapGenerator) > 0 || len(k.SecretGenerator) > 0 || len(k.Generators) > 0 ||
		len(k.Transformers) > 0 || len(k.Bases) > 0 || len(k.CRDs) > 0 ||
		k.NamePrefix != "" || k.NameSuffix != "" || k.Namespace != "" ||
		len(k.CommonLabels) > 0 || len(k.CommonAnnotations) > 0
}

// checkCustomLayout validates the escape-hatch tree at customDir (an apl-values dir
// joined with clusterspec.CustomSubdir). It returns nil when there is nothing to say —
// including when custom/ is absent entirely, which is the template-repo case and the
// case for any caller pointed at a tree that has no instance scaffold.
//
// Every finding is an error rather than a warning: each one either destroys operator
// workloads on the next sync (the flat root) or produces an Application that fights
// apl-core or itself (the reserved names).
func checkCustomLayout(customDir string) error {
	if _, err := os.Stat(customDir); err != nil {
		return nil // no escape hatch in this tree — nothing to check.
	}

	flat, err := checkFlatRoot(customDir)
	if err != nil {
		return err
	}
	findings := append(flat, checkNamespaceDirs(customDir)...)
	if len(findings) == 0 {
		return nil
	}
	msg := "  • " + strings.Join(findings, "\n\n  • ")
	// The migration block is long and identical for every flat-layout finding — append
	// it ONCE, and only when something actually needs migrating (a reserved namespace
	// name is a rename, not a migration).
	if len(flat) > 0 {
		msg += "\n\n" + migrationHint()
	}
	return errors.New(msg)
}

// checkFlatRoot returns one finding per symptom of the pre-ApplicationSet flat layout
// still being in place AND carrying content: a kustomization.yaml at custom/'s root, or
// loose manifests beside it. The error return is reserved for a tree it cannot read.
func checkFlatRoot(customDir string) ([]string, error) {
	var findings []string

	// An EMPTY kustomization.yaml (the untouched starter the template used to ship) is
	// inert: nothing was ever deployed through it, so nothing can be cascade-deleted.
	// Leave it alone rather than failing a fresh instance that never used the hatch.
	kPath := filepath.Join(customDir, "kustomization.yaml")
	if b, err := os.ReadFile(kPath); err == nil {
		var k flatKustomization
		if err := yaml.Unmarshal(b, &k); err != nil {
			// Unparseable: cannot prove it is the empty starter, so assume content.
			findings = append(findings, fmt.Sprintf("%s: unparseable (%v) — cannot prove it is the empty starter, so it is treated as carrying content.", kPath, err))
		} else if k.carriesContent() {
			findings = append(findings, fmt.Sprintf("%s still uses the FLAT layout and carries content.", kPath))
		}
	}

	// Loose manifests directly under custom/ are unreachable in the new layout: the
	// generators only match namespaces/* and global/. Silently-unapplied resources are
	// worse than a failed render.
	entries, err := os.ReadDir(customDir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", customDir, err)
	}
	var stray []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if name == "kustomization.yaml" || !isManifestFile(name) {
			continue
		}
		stray = append(stray, name)
	}
	if len(stray) > 0 {
		sort.Strings(stray)
		findings = append(findings, fmt.Sprintf("%s: manifests sit directly in the custom/ root and would NOT be applied: %s",
			customDir, strings.Join(stray, ", ")))
	}
	return findings, nil
}

// checkNamespaceDirs returns one finding per namespaces/<ns> directory whose name would
// collide with apl-core's own gitops Applications or with the generated global App.
func checkNamespaceDirs(customDir string) []string {
	nsDir := filepath.Join(customDir, clusterspec.CustomNamespacesDirName)
	entries, err := os.ReadDir(nsDir)
	if err != nil {
		return nil // no namespaces/ yet — the generator yields zero Apps. Fine.
	}
	var findings []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		switch {
		case strings.HasPrefix(name, aplReservedPrefix):
			findings = append(findings, fmt.Sprintf(
				"%s: %q is an apl-core-owned namespace (the %q prefix is reserved). apl-core's own gitops-ns-%s Application already manages it, and a second Argo CD Application over the same resources puts them in contention. Deploy into a namespace you own instead.\n"+
					"    See https://techdocs.akamai.com/app-platform/docs/gitops (\"do not add, edit, or delete files in any apl- prefixed directory\").",
				filepath.Join(nsDir, name), name, aplReservedPrefix, name))
		case name == clusterspec.CustomGlobalDirName:
			findings = append(findings, fmt.Sprintf(
				"%s: %q is reserved. Its generated Application name (instance-custom-%s) would collide with the one the custom/%s/ generator emits. Rename the directory, or move cluster-scoped resources to custom/%s/.",
				filepath.Join(nsDir, name), name, name, clusterspec.CustomGlobalDirName, clusterspec.CustomGlobalDirName))
		}
	}
	return findings
}

// isManifestFile reports whether name looks like a Kubernetes manifest an operator would
// have expected to be applied.
func isManifestFile(name string) bool {
	ext := strings.ToLower(filepath.Ext(name))
	return ext == ".yaml" || ext == ".yml" || ext == ".json"
}

// migrationHint is the one actionable block every flat-layout finding ends with. It is
// deliberately explicit about the consequence: an operator who skims will still see that
// rendering past this point deletes their workloads.
func migrationHint() string {
	return "  The escape hatch now follows App Platform's GitOps layout:\n" +
		"      " + clusterspec.CustomRoot + "/" + clusterspec.CustomNamespacesDirName + "/<namespace>/   your namespaced resources\n" +
		"      " + clusterspec.CustomRoot + "/" + clusterspec.CustomGlobalDirName + "/               cluster-scoped resources (CRDs, ClusterRoles, ...)\n" +
		"\n" +
		"  MIGRATE (this is not automatic — custom/ is yours, so nothing may rewrite it):\n" +
		"    1. Move each manifest into " + clusterspec.CustomNamespacesDirName + "/<its namespace>/, or into " + clusterspec.CustomGlobalDirName + "/ if cluster-scoped.\n" +
		"       A per-directory kustomization.yaml is optional — a plain directory of manifests\n" +
		"       is recursed as-is; add one only if you need kustomize features.\n" +
		"    2. Delete the flat " + clusterspec.CustomRoot + "/kustomization.yaml.\n" +
		"    3. Re-run `llz render`.\n" +
		"\n" +
		"  WHY THIS BLOCKS: the flat layout's `instance-custom` Application has a resources\n" +
		"  finalizer, and the platform-bootstrap app-of-apps prunes. Rendering the new\n" +
		"  ApplicationSet over it would prune that Application and CASCADE-DELETE every\n" +
		"  workload you deployed through the hatch. Moving the files first makes the\n" +
		"  changeover additive. See docs/extending-llz.md."
}
