package main

// extension_provision.go solves the SUPPLY side of extension tools for the host/local
// case (the Configure-phase ActionProvision). Extensions DECLARE pinned tool specs
// (extTool.Via + Version — a mise backend ref like "pipx:yamllint" + a version); llz
// aggregates the enabled set into a generated .mise.toml and provisions it with `mise`,
// a real, checksum-aware version manager.
//
// The trust boundary (why this is safe for REMOTE extensions): the extension is DATA on
// the supply path, never code. It names a registry-resolvable, pinned ref; it cannot
// ship an install script for llz to run on the host (there is no such field). mise
// installs from its backends' registries (pip/npm/aqua) with the pins; the binary
// backends (aqua/ubi) verify checksums. The version pins ride the extension's existing
// SHA+digest source lock, and the install itself is gated (--yes), like first-enable.
// So a remote extension may REQUEST a pinned tool; it cannot execute on your machine.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const miseConfigPath = ".mise.toml"

// provisionableTools returns the enabled set's tools that carry a mise spec (Via set),
// de-duplicated by Via ref. Tools with no Via are operator-supplied (declared + verified
// but not auto-provisioned) and are skipped here.
func provisionableTools(exts []Extension) []extTool {
	seen := map[string]bool{}
	var out []extTool
	for _, e := range exts {
		for _, t := range e.Manifest.Tools {
			if t.Via == "" || seen[t.Via] {
				continue
			}
			seen[t.Via] = true
			out = append(out, t)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Via < out[j].Via })
	return out
}

// renderMiseConfig emits the managed .mise.toml from the enabled extensions' pinned tool
// specs. Pure + deterministic (sorted) so it unit-tests and feeds a --check drift gate,
// like the workflow generators.
func renderMiseConfig(exts []Extension) string {
	var b strings.Builder
	b.WriteString("# GENERATED by `llz extension provision` from enabled extensions' tools:.\n" +
		"# DO NOT EDIT BY HAND — re-run it after enabling/disabling an extension. Each entry\n" +
		"# is a pinned mise backend ref; `mise install` provisions them (checksum-verified\n" +
		"# for the binary backends). --check is the drift gate.\n\n" +
		"[tools]\n")
	for _, t := range provisionableTools(exts) {
		b.WriteString(fmt.Sprintf("%q = %q\n", t.Via, t.Version))
	}
	return b.String()
}

// miseInstallFn runs `mise` over the generated config: trust the llz-generated file, then
// install. Seamed so provisioning unit-tests without a real mise.
var miseInstallFn = func(g globalOpts, root, config string) error {
	if !haveTool("mise") {
		return fmt.Errorf("mise is not installed — it is the provisioner (https://mise.jdx.dev); install it, then re-run")
	}
	for _, args := range [][]string{{"trust", config}, {"install"}} {
		cmd := exec.Command("mise", args...)
		cmd.Dir = root
		cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("mise %s: %w", strings.Join(args, " "), err)
		}
	}
	return nil
}

// runExtensionProvision regenerates .mise.toml from the enabled set and installs the
// pinned tools with mise (the Configure-phase ActionProvision). Host-mutating (it
// installs binaries), so it is gated: --dry-run / no --yes prints the plan and writes
// nothing. --check reports drift in the generated config without installing.
func runExtensionProvision(g globalOpts, root string, check bool) error {
	exts, err := loadEnabledExtensions(root)
	if err != nil {
		return err
	}
	tools := provisionableTools(exts)
	out := filepath.Join(root, miseConfigPath)

	if len(tools) == 0 {
		if _, statErr := os.Stat(out); statErr == nil && !check {
			fmt.Fprintf(os.Stderr, "%s: no provisionable tools — leaving it in place (operator-owned?)\n", out)
		}
		fmt.Fprintln(os.Stderr, "no enabled extension declares a provisionable tool (via:)")
		return nil
	}

	want := renderMiseConfig(exts)
	got, _ := os.ReadFile(out)
	if check {
		if string(got) != want {
			return fmt.Errorf("%s is out of date with the enabled extensions — run `llz extension provision`", out)
		}
		fmt.Fprintf(os.Stderr, "%s: up to date (%d tool(s))\n", out, len(tools))
		return nil
	}

	if !proceedGated(g, ActionProvision) {
		fmt.Fprintf(os.Stderr, "→ would write %s and `mise install`:\n", out)
		for _, t := range tools {
			fmt.Fprintf(os.Stderr, "    %s@%s  (%s)\n", t.Via, t.Version, t.Name)
		}
		if !g.yes && !g.dryRun {
			fmt.Fprintln(os.Stderr, "  (re-run with --yes to write + install)")
		}
		return nil
	}

	if string(got) != want {
		if err := os.WriteFile(out, []byte(want), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "%s: wrote (%d tool(s))\n", out, len(tools))
	}
	return miseInstallFn(g, root, miseConfigPath)
}
