package main

// spec_helpers.go is the single entry every command uses to become spec-aware.
// The LandingZone spec (landingzone.yaml + environments/<env>.yaml) is the source
// of truth; the committed tfvars are derived (regenerated by `llz render`, and at
// build time by CI). So a command that reads rendered tfvars should prefer the
// spec when one is present — otherwise it reports STALE data after a spec edit that
// wasn't re-rendered. loadSpec centralizes that "spec present?" decision.

import (
	"path/filepath"

	"github.com/akamai-consulting/lke-landing-zone/tools/internal/clusterspec"
)

// loadSpec loads the assembled LandingZone spec at the instance root, reporting
// whether one is present. present=false (with nil error) means a pre-spec instance
// — callers fall back to reading the committed tfvars. A non-nil error means a spec
// IS present but failed to load/parse (the caller should surface it).
func loadSpec() (lz *clusterspec.LandingZone, present bool, err error) {
	tfDir, _, _ := instanceLayout()
	specRoot := filepath.Dir(tfDir)
	if !clusterspec.InstancePresent(specRoot) {
		return nil, false, nil
	}
	lz, err = clusterspec.LoadInstance(specRoot)
	return lz, true, err
}
