package tfroots

import (
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"
)

// wantRoots is the day-0 TF root set the embed must produce, asserted here as
// test-local expected data rather than read back from the package (which would
// make the test echo the implementation). The former cluster-bootstrap root was
// retired — its in-cluster bootstrap runs natively via `llz ci bootstrap-cluster`.
var wantRoots = []string{"cluster", "databases", "object-storage", "vpc"}

// TestFilesProducesTokenFreeTF is the former TestRenderWritesTokenFreeTF,
// retargeted at Files (the live API) after the write-to-disk Render half of this
// package was retired — the render engine iterates Files() and writes via its own
// writeTargets. The assertions: every root lands its full *.tf set, the ONLY
// non-.tf file produced is a root's provider lockfile, no copier token survives, a
// static file is byte-identical to the embed, and a token-bearing file reflects
// the values.
//
// THE LOCKFILE IS THE ONE ALLOWED EXCEPTION, named rather than pattern-matched.
// Files emits it so the pin and the constraint that governs it are laid down
// together (see lockRel); everything else non-.tf reaching an instance's roots —
// a stray README, a tfvars.example — is still a bug, and widening this arm to
// "anything the embed happens to hold" would stop saying so.
func TestFilesProducesTokenFreeTF(t *testing.T) {
	dst := t.TempDir()
	files := Files(dst, "akamai-consulting", "v9.9.9")
	if len(files) == 0 {
		t.Fatal("Files produced nothing")
	}

	byRoot := map[string]map[string]bool{}
	for p, content := range files {
		isLock := filepath.Base(p) == LockFile
		if !strings.HasSuffix(p, ".tf") && !isLock {
			t.Errorf("Files produced a file that is neither .tf nor %s: %s", LockFile, p)
		}
		if strings.HasSuffix(p, "terraform.tfvars.example") {
			t.Errorf("Files must not produce a tfvars.example: %s", p)
		}
		if strings.HasSuffix(p, "README.md") {
			t.Errorf("Files must not produce a README.md: %s", p)
		}
		rel, err := filepath.Rel(filepath.Join(dst, "terraform-iac-bootstrap"), p)
		if err != nil {
			t.Fatalf("rel: %v", err)
		}
		parts := strings.SplitN(rel, string(filepath.Separator), 2)
		if byRoot[parts[0]] == nil {
			byRoot[parts[0]] = map[string]bool{}
		}
		byRoot[parts[0]][parts[1]] = true
		if isLock {
			continue // generated by tofu init; carries no copier token by construction
		}

		if strings.Contains(content, "<@") {
			t.Errorf("%s still has an unsubstituted copier token:\n%s", p, content)
		}
	}

	for _, root := range wantRoots {
		f := byRoot[root]
		if f == nil {
			t.Errorf("root %q produced no .tf files", root)
			continue
		}
		for _, must := range []string{"backend.tf", "versions.tf", "main.tf"} {
			if !f[must] {
				t.Errorf("root %q missing %s", root, must)
			}
		}
	}
	if len(byRoot) != len(wantRoots) {
		t.Errorf("Files produced roots %v, want %v", byRoot, wantRoots)
	}

	// backend.tf is static (no token) → substitution leaves it identical to the embed.
	rawBackend, err := embedded.ReadFile("roots/cluster/backend.tf")
	if err != nil {
		t.Fatal(err)
	}
	if got := files[filepath.Join(dst, "terraform-iac-bootstrap", "cluster", "backend.tf")]; string(rawBackend) != got {
		t.Errorf("static backend.tf changed under substitution")
	}

	// A token-bearing file must reflect the substituted values.
	clusterMain := files[filepath.Join(dst, "terraform-iac-bootstrap", "cluster", "main.tf")]
	if !strings.Contains(clusterMain, "akamai-consulting/lke-landing-zone.git//terraform-modules/llz-cluster?ref=v9.9.9") {
		t.Errorf("cluster/main.tf tokens not substituted:\n%s", clusterMain)
	}
}

func TestTfvarsExample(t *testing.T) {
	for _, root := range wantRoots {
		b, err := TfvarsExample(root)
		if err != nil {
			t.Errorf("TfvarsExample(%q): %v", root, err)
			continue
		}
		if len(b) == 0 {
			t.Errorf("TfvarsExample(%q) is empty", root)
		}
	}
	if _, err := TfvarsExample("nope"); err == nil {
		t.Errorf("TfvarsExample of a bogus root should error")
	}
}

func TestSubstitute(t *testing.T) {
	in := "org=<@ upstream_org @> ref=<@ llz_version @>"
	got := Substitute(in, "akamai-consulting", "v1.2.3")
	want := "org=akamai-consulting ref=v1.2.3"
	if got != want {
		t.Errorf("Substitute = %q, want %q", got, want)
	}
}

// TestDefaultVPCSubnetCIDRMatchesRoot ties DefaultVPCSubnetCIDR to the HCL it
// claims to mirror. internal/terraform and internal/clusterspec both alias the
// constant, so a change to the root's default that is not reflected in Go — or
// vice versa — fails here rather than silently producing a VPC_CIDR that
// disagrees with what Terraform actually applied.
func TestDefaultVPCSubnetCIDRMatchesRoot(t *testing.T) {
	raw, err := embedded.ReadFile("roots/cluster/variables.tf")
	if err != nil {
		t.Fatalf("read embedded cluster/variables.tf: %v", err)
	}

	// Scan forward from the `vpc_subnet_cidr` block header to its `default =`.
	lines := strings.Split(string(raw), "\n")
	idx := -1
	for i, l := range lines {
		if strings.HasPrefix(strings.TrimSpace(l), `variable "vpc_subnet_cidr"`) {
			idx = i
			break
		}
	}
	if idx < 0 {
		t.Fatal(`no variable "vpc_subnet_cidr" block in roots/cluster/variables.tf`)
	}

	want := ""
	for _, l := range lines[idx:] {
		s := strings.TrimSpace(l)
		if s == "}" {
			break
		}
		if strings.HasPrefix(s, "default") {
			if _, v, ok := strings.Cut(s, "="); ok {
				want = strings.Trim(strings.TrimSpace(v), `"`)
			}
			break
		}
	}
	if want == "" {
		t.Fatal("vpc_subnet_cidr block has no default = ... line")
	}
	if want != DefaultVPCSubnetCIDR {
		t.Errorf("DefaultVPCSubnetCIDR = %q, but roots/cluster/variables.tf defaults to %q", DefaultVPCSubnetCIDR, want)
	}
}

// THE GATE ON THE `all:` EMBED PREFIX, and the reason it is a test rather than a
// comment.
//
// A bare `//go:embed roots` silently skips every file whose name begins with `.`,
// so the roots' .terraform.lock.hcl would be absent from the binary with no build
// error, no vet complaint and no failing assertion anywhere else. Files would emit
// no lock, `llz render` would write lockless roots into every instance, and `tofu
// init` would resolve providers fresh on each run under a plan nobody reviewed —
// the exact un-pinning the lock exists to prevent, arriving as silence. Measured:
// before the prefix was added this walk found zero lock files.
//
// It compares the EMBED against the DISK rather than asserting a hardcoded list,
// so it also catches the other direction — a lock added to a root that the embed
// then drops, and a lock the embed carries that no longer exists.
func TestEveryOnDiskLockIsEmbedded(t *testing.T) {
	entries, err := os.ReadDir("roots")
	if err != nil {
		t.Fatalf("read roots/: %v", err)
	}
	var onDisk []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join("roots", e.Name(), LockFile)); err == nil {
			onDisk = append(onDisk, e.Name()+"/"+LockFile)
		}
	}
	if len(onDisk) == 0 {
		t.Fatal("no root holds a " + LockFile + " on disk — either they moved, or this test is now " +
			"asserting nothing. It cannot tell the difference, so it fails.")
	}
	sort.Strings(onDisk)
	if !slices.Equal(onDisk, lockRel) {
		t.Fatalf("embedded lockfiles = %v, on disk = %v — a mismatch means `//go:embed all:roots` "+
			"lost its `all:` prefix (the embed silently drops dotfiles) or a root's lock moved", lockRel, onDisk)
	}

	// The embed carrying them is only half the point: Files is what a render
	// consumes, and a lock that never reaches its map is a lock no instance gets.
	files := Files("/inst", "acme", "v1.2.3")
	for _, rel := range onDisk {
		want := filepath.Join("/inst", "terraform-iac-bootstrap", rel)
		body, ok := files[want]
		if !ok {
			t.Errorf("Files() does not emit %s — `llz render` would leave that root unlocked", want)
			continue
		}
		if !strings.Contains(body, "provider \"") {
			t.Errorf("%s carries no provider stanza:\n%s", want, body)
		}
	}
}

// The locks are emitted VERBATIM. Substitute fills the two copier tokens and a
// lockfile carries neither, so running one through it is a no-op today — and a
// silent corruption on the day a provider hash happens to contain the token text.
func TestLocksAreEmittedWithoutTokenSubstitution(t *testing.T) {
	for rel, body := range Files("/inst", "acme", "v1.2.3") {
		if filepath.Base(rel) != LockFile {
			continue
		}
		raw, err := embedded.ReadFile("roots/" + filepath.Base(filepath.Dir(rel)) + "/" + LockFile)
		if err != nil {
			t.Fatalf("read embedded lock for %s: %v", rel, err)
		}
		if body != string(raw) {
			t.Errorf("%s was rewritten on the way out of Files()", rel)
		}
	}
}
