package health

import (
	"encoding/json"
	"fmt"
	"strings"
)

// argo.go ports section 2 (ArgoCD Applications) — the script's most intricate
// classification: the order in which an Application's sync/health/automated/
// spec-error state, the operator-deferred allowlist, and the Phase-1 cascade
// resolve to pass/fail/pending/deferred/drift.

// ArgoApp is the extracted status of one ArgoCD Application.
type ArgoApp struct {
	Name      string
	Sync      string // .status.sync.status
	Health    string // .status.health.status
	Automated bool   // .spec.syncPolicy.automated present (non-null)
	SpecErr   string // joined ComparisonError/InvalidSpecError condition messages
	OpErr     string // .status.operationState.message when the last sync FAILED (apply-time errors, e.g. the 256KB annotation limit — these never surface as a ComparisonError)
	// Drifted names the child resources whose own .status is not Synced —
	// <kind>/<ns>/<name>, in .status.resources order. An OutOfSync App says
	// only THAT something differs; this says WHAT, which is the difference
	// between a DRIFT line an operator can act on and one they learn to skip
	// past (#394). Empty when nothing is individually OutOfSync (an App can be
	// OutOfSync for a resource Argo cannot attribute, e.g. a pruned extra).
	Drifted []string
	// SyncErr is the message of a sync operation that is FAILING AND RETRYING —
	// phase still "Running", tasks reported unsuccessful. See ParseArgoApp.
	SyncErr string
	// Project is .spec.project — the AppProject scoping this Application, and the
	// authority on whether it is platform or instance-owned. See
	// health.InstanceCustomProject.
	Project string
	// Resources is every resource this Application declares (.status.resources),
	// which is what lets ownership follow the platform/instance boundary DOWN from
	// the Application to its ExternalSecrets, Deployments, Workflows and Pods.
	// Already fetched — Drifted is derived from the same list.
	Resources []ResourceRef
	// DestNamespace is .spec.destination.namespace — where this Application puts
	// what it does not namespace itself.
	//
	// IT IS ONLY READ WHEN Resources IS EMPTY. An Application Argo has not compared
	// publishes nothing, so the ownership index has to assume it could own
	// something; the destination is the only evidence available about WHERE. An
	// empty value means "could be anywhere", which is the fail-closed reading. See
	// OwnershipIndex.platformMayClaim.
	DestNamespace string
}

// SyncTasksFailing reports whether an operationState message describes a sync
// whose tasks failed, as opposed to one merely in flight. Argo phrases both under
// phase "Running"; only the failing one carries this sentence.
func SyncTasksFailing(msg string) bool {
	return strings.Contains(msg, "synchronization tasks completed unsuccessfully")
}

// maxDriftedNamed caps how many drifted resources a DRIFT line names. A report
// line is read at a glance; an App that drifts on 40 resources has a different
// problem, and the count in the "+N more" tail is the part that matters there.
const maxDriftedNamed = 3

// summarizeDrifted renders the drifted-resource suffix for a report line, or ""
// when there is nothing to name. Truncation is EXPLICIT: a silently-capped list
// reads as the whole story.
func summarizeDrifted(drifted []string) string {
	if len(drifted) == 0 {
		return ""
	}
	shown := drifted
	tail := ""
	if len(shown) > maxDriftedNamed {
		shown, tail = shown[:maxDriftedNamed], fmt.Sprintf(" +%d more", len(drifted)-maxDriftedNamed)
	}
	return " [OutOfSync: " + strings.Join(shown, ", ") + tail + "]"
}

// IsInstanceCustomApp reports whether an ArgoCD Application is an operator
// escape-hatch app generated by the instance-custom ApplicationSet from
// kubernetes-custom/namespaces/<ns>/ (named instance-custom-<ns>). These are
// instance-OWNED (.template-manifest classifies kubernetes-custom/ as `owned`, not
// `managed`), not platform components.
func IsInstanceCustomApp(name string) bool {
	return strings.HasPrefix(name, instanceCustomAppPrefix)
}

// IsInstanceOwnedApp is the boundary Report.RouteApp and the ownership index both
// read: an Application scoped to the instance-custom AppProject, or one named by
// the escape-hatch ApplicationSet's convention.
//
// THE PROJECT IS THE AUTHORITY; the name prefix is kept as a second signal, not
// as the definition. Keying on the name ALONE is what let nine instance-owned
// Applications gate the platform on akamai/gsap-apl: the managed-apps
// ApplicationSet names its Applications after the app (`dispatch`,
// `account-health`) while stamping `project: instance-custom` on every one. The
// prefix stays because it costs nothing and covers an Application whose project
// could not be read.
//
// FAILS CLOSED: an Application in any other project — or in none we recognise —
// is platform, and gates.
func IsInstanceOwnedApp(a ArgoApp) bool {
	return a.Project == InstanceCustomProject || IsInstanceCustomApp(a.Name)
}

// THERE IS NO EXPORTED classify-and-demote. There was — ClassifyArgoApp — and it
// returned the demoted category WITHOUT recording it, so every caller had to
// remember to bank the severity the demotion had just consumed. Callers forgot,
// which is how a hard-failed instance-owned Application came to gate NEITHER
// scope. Report.RouteApp is the only way in: it classifies, applies the boundary,
// and records the pre-demotion severity in one call. The tests reach the same
// funnel through classifyApp (argo_test.go) rather than around it.

// classifyArgoApp applies section 2's decision order to one Application:
//  1. operator-deferred (EXTERNAL_DEP_APPS) wins even over a spec error, since
//     some deferrals surface AS a ComparisonError (e.g. an operator-supplied token missing);
//  2. a persistent ComparisonError/InvalidSpecError is a real failure;
//  3. Synced+Healthy passes;
//  4. no automated syncPolicy => intentionally hand-managed => pending;
//  5. Phase-1 cascade apps waiting on OpenBao => pending;
//  6. OutOfSync but Healthy => cosmetic drift;
//  7. Progressing => reconcile still in flight => pending (poll, don't fail);
//  8. otherwise => fail.
//
// The instance-custom remap is layered on top by Report.RouteApp.
func classifyArgoApp(a ArgoApp, phase1 bool) (Category, string) {
	label := fmt.Sprintf("%s (%s/%s)", a.Name, a.Sync, a.Health)
	if reason, ok := MatchExternalDep(a.Name, ExternalDepApps()); ok {
		return CatDeferred, label + " — " + reason
	}
	// A sync that failed on the 256KB metadata.annotations limit ("... is invalid:
	// metadata.annotations: Too long") is an infra wedge, not an app-config fault:
	// a CRD (or other object) carries an oversized client-side last-applied-
	// configuration annotation, so every apply to it fails. The convergence gate
	// self-heals by stripping that annotation and re-polling (see runConverge), so
	// treat it as transient/pending rather than a hard strike — same rationale as
	// the argocd-redis auth split above.
	if IsAnnotationLimitError(a.OpErr) {
		return CatPending, label + " — sync hit the 256KB annotation limit; converge strips the oversized CRD annotation and re-polls"
	}
	if a.SpecErr != "" {
		// A ComparisonError carrying a Redis auth code (WRONGPASS/NOAUTH) is not an
		// app-config fault: it is the ArgoCD repo-server failing to authenticate to
		// its argocd-redis manifest cache, so *every* Application ComparisonErrors
		// at once. That happens when the argocd-redis password rotates under a
		// never-restarted redis pod (a reused-cluster e2e can leave redis holding a
		// stale --requirepass while freshly-rolled repo-servers read the new secret).
		// A `rollout restart deploy/argocd-redis` realigns them, so this is a
		// transient infra condition to POLL on — same treatment as a Progressing
		// rollout — not a hard strike. A genuine per-app spec error never carries a
		// Redis auth code, so the reclassification cannot mask a real failure. The
		// convergence gate now self-heals this by restarting argocd-redis once when
		// it observes the split persisting across polls (see runConverge); worst
		// case (restart ineffective) the gate simply exhausts its budget and exits 1.
		if IsRepoServerCacheAuthError(a.SpecErr) {
			return CatPending, label + " — argocd-redis cache auth (repo-server↔redis password split); transient, polling"
		}
		// A GIT auth refusal, by contrast, is terminal. Argo is being told "no" by
		// the remote for the credential it holds; polling cannot change the answer,
		// and nothing in the bootstrap re-mints that credential. Saying so here —
		// rather than letting it ride as a generic CatFail that phase1 then
		// downgrades to in-progress — is what stops the gate from spending its
		// entire budget on a question already answered. Checked AFTER the Redis case
		// because Redis's NOAUTH message is literally "NOAUTH Authentication
		// required." and would otherwise match.
		if IsGitAuthError(a.SpecErr) {
			return CatFail, label + " — " + a.SpecErr +
				"  ⇒ TERMINAL: Argo CD cannot authenticate to the source repo. Polling will not fix this. " +
				"Check the values-repo credential (APL_VALUES_REPO_TOKEN → otomi.git.password → the argocd " +
				"repo Secret), and that the repo Secret actually materialized — it arrives via an ExternalSecret, " +
				"so it stays empty if external-secrets never installed."
		}
		return CatFail, label + " — " + a.SpecErr
	}
	if a.Sync == "Synced" && a.Health == "Healthy" {
		return CatOK, label
	}
	if !a.Automated {
		return CatPending, label + " — sync suspended (no automated policy)"
	}
	if phase1 && MatchPrefix(a.Name, Phase1PendingApps()) {
		return CatPending, label + " — waiting on OpenBao bootstrap"
	}
	// BEFORE the drift branch. An Application whose sync keeps failing is not
	// "drift only, workload functional" — the resources it could not apply may
	// never have existed. Reported as PENDING rather than FAIL because Argo is
	// still retrying and the early attempts of a young cluster do clear (a
	// namespace that arrives a wave later); the convergence budget bounds it, and
	// the budget-exhaustion report names what was outstanding. What must not
	// happen is the message being discarded and the app called functional.
	if a.SyncErr != "" {
		detail := " — sync is FAILING and retrying: " + FirstLine(a.SyncErr) + summarizeDrifted(a.Drifted)
		return PendingIfBudgeted(label+detail,
			label+detail+"  ⇒ this is a steady-state check: the sync has been retrying past any startup "+
				"window, so the resources it cannot apply are not going to appear on their own")
	}
	if a.Health == "Healthy" {
		return CatDrift, label + " — drift only; workload functional" + summarizeDrifted(a.Drifted)
	}
	// Progressing is ArgoCD's "reconcile still in flight" health — a Deployment
	// rolling out, a child resource not yet Ready (e.g. loki-gateway waiting on
	// its loki backend). That is the canonical in-progress state the convergence
	// gate must POLL on, not hard-fail. A genuinely stuck rollout flips to
	// Degraded (caught below) once progressDeadlineSeconds lapses, and the gate's
	// overall budget bounds the poll — so treating it as pending cannot hang.
	if a.Health == "Progressing" {
		return CatPending, label + " — rolling out (Progressing)"
	}
	return CatFail, label
}

// IsRepoServerCacheAuthError reports whether a ComparisonError message carries a
// Redis authentication code. The ArgoCD repo-server caches git refs/manifests in
// argocd-redis; when its AUTH fails (e.g. the redis password rotates under a
// never-restarted redis pod), ListRefs returns "failed to list refs: WRONGPASS
// ..." and the Application goes Unknown/ComparisonError. WRONGPASS ("invalid
// username-password pair") and NOAUTH ("authentication required") originate only
// in the redis cache path, never in an Application's own source, so they mark a
// transient infra blip the convergence gate should poll on rather than a real
// spec fault.
func IsRepoServerCacheAuthError(specErr string) bool {
	return strings.Contains(specErr, "WRONGPASS") || strings.Contains(specErr, "NOAUTH")
}

// IsGitAuthError reports whether a ComparisonError message is the git remote
// refusing Argo's credential — as opposed to a network flake, a manifest fault,
// or the Redis cache split above.
//
// The distinction is the whole point: a converge run has spent its entire 1200s
// budget polling this —
//
//	gitops-global (Unknown/Healthy) — ComparisonError: failed to list refs:
//	  authentication required: Unauthorized
//
// Nothing about that resolves by waiting. The remote answered, the answer was
// "no", and it will keep being "no" until an operator fixes the credential. Every
// other failure in that run — external-secrets CRDs absent, apl-sops-secrets
// missing, apl-operator in CreateContainerConfigError, Harbor's registry down —
// was downstream of it, so 20 minutes of polling bought nothing but a longer log.
//
// Deliberately NOT matched: "repository not found" (a private repo returns it to
// a credential that cannot see it, but so does a genuinely wrong repoURL, and the
// two are indistinguishable from the message alone) and bare "403" (Argo wraps
// several unrelated upstream 403s). Both stay generic failures. Callers must test
// IsRepoServerCacheAuthError FIRST — Redis's NOAUTH text contains "authentication
// required" and is transient, the exact opposite verdict.
func IsGitAuthError(specErr string) bool {
	if specErr == "" || IsRepoServerCacheAuthError(specErr) {
		return false
	}
	m := strings.ToLower(specErr)
	for _, p := range []string{
		"authentication required",                // go-git's 401 on ref discovery
		"invalid username or password",           // git-over-HTTPS credential rejection
		"authentication failed",                  // generic transport refusal
		"could not read username",                // no credential at all, prompts disabled
		"terminal prompts disabled",              // ditto
		"ssh: handshake failed",                  // key-based remote rejecting the key
		"permission denied (publickey",           // ditto
		"write access to repository not granted", // valid token, insufficient scope
	} {
		if strings.Contains(m, p) {
			return true
		}
	}
	return false
}

// IsAnnotationLimitError reports whether a sync/operation error message carries
// the Kubernetes 256KB metadata.annotations cap ("metadata.annotations: Too
// long"). It's raised when applying an object whose client-side last-applied-
// configuration annotation is oversized — most often a CRD with a huge embedded
// OpenAPI schema (Kyverno policy CRDs, Gateway-API httproutes). The convergence
// gate strips that annotation to unwedge the apply, so this marks a self-healable
// transient rather than a real spec fault.
func IsAnnotationLimitError(msg string) bool {
	return strings.Contains(msg, "annotations: Too long")
}

// argoAppJSON is the subset of an ArgoCD Application object we parse.
type argoAppJSON struct {
	Metadata struct {
		Name string `json:"name"`
	} `json:"metadata"`
	Spec struct {
		Project     string `json:"project"`
		Destination struct {
			Namespace string `json:"namespace"`
		} `json:"destination"`
		SyncPolicy struct {
			Automated json.RawMessage `json:"automated"`
		} `json:"syncPolicy"`
	} `json:"spec"`
	Status struct {
		Sync struct {
			Status string `json:"status"`
		} `json:"sync"`
		Health struct {
			Status string `json:"status"`
		} `json:"health"`
		Conditions []struct {
			Type    string `json:"type"`
			Message string `json:"message"`
		} `json:"conditions"`
		OperationState struct {
			Phase   string `json:"phase"`
			Message string `json:"message"`
		} `json:"operationState"`
		Resources []struct {
			Group     string `json:"group"`
			Kind      string `json:"kind"`
			Name      string `json:"name"`
			Namespace string `json:"namespace"`
			Status    string `json:"status"`
		} `json:"resources"`
	} `json:"status"`
}

// ParseArgoApp extracts an ArgoApp from one Application's JSON, joining any
// ComparisonError/InvalidSpecError condition messages (the authoritative
// "spec can't render" signal) and resolving the automated-syncPolicy flag —
// the same fields the APP_OUT jq pulls.
func ParseArgoApp(raw []byte) (ArgoApp, error) {
	var j argoAppJSON
	if err := json.Unmarshal(raw, &j); err != nil {
		return ArgoApp{}, err
	}
	var specErrs []string
	for _, c := range j.Status.Conditions {
		if c.Type == "ComparisonError" || c.Type == "InvalidSpecError" {
			msg := c.Message
			if msg == "" {
				msg = "(no message)"
			}
			specErrs = append(specErrs, c.Type+": "+msg)
		}
	}
	auto := len(j.Spec.SyncPolicy.Automated) > 0 && strings.TrimSpace(string(j.Spec.SyncPolicy.Automated)) != "null"
	// A FAILED sync surfaces its apply-time error in operationState.message (never
	// as a ComparisonError). Only carry it when the phase actually failed, so a
	// Succeeded/Running message can't be mistaken for an error.
	opErr := ""
	if j.Status.OperationState.Phase == "Failed" || j.Status.OperationState.Phase == "Error" {
		opErr = j.Status.OperationState.Message
	}
	// A RETRYING SYNC KEEPS PHASE "Running" WHILE FAILING, and discarding its
	// message cost a release-e2e round. Argo retries a failed sync in place: the
	// phase stays Running and the message becomes
	//
	//	one or more synchronization tasks completed unsuccessfully, reason:
	//	admission webhook "mutate.kyverno.svc-ignore" denied the request …
	//	MANIFEST_UNKNOWN … Retrying attempt #15
	//
	// Because the phase was not Failed, that text was dropped; the app then read
	// as OutOfSync/Healthy and was graded "drift only; workload functional" — of
	// an Application whose Deployment had never been created. The gate looked past
	// the actual blocker and waited out its budget on a downstream symptom.
	syncErr := ""
	if j.Status.OperationState.Phase == "Running" && SyncTasksFailing(j.Status.OperationState.Message) {
		syncErr = j.Status.OperationState.Message
	}
	// A resource with an EMPTY status is not drift: Argo leaves .status blank on
	// resources it does not diff (hooks, and children it only observes). Only an
	// explicit non-Synced value names a difference.
	// One pass over .status.resources feeds two consumers: `drifted` (which
	// resources differ) and `resources` (which resources this App DECLARES,
	// regardless of sync state — the ownership index's authority). Keeping them
	// together is deliberate: they must describe the same list, and reading the
	// list twice invites them to diverge.
	var drifted []string
	resources := make([]ResourceRef, 0, len(j.Status.Resources))
	for _, r := range j.Status.Resources {
		resources = append(resources, ResourceRef{Group: r.Group, Kind: r.Kind, Namespace: r.Namespace, Name: r.Name})
		if r.Status == "" || r.Status == "Synced" {
			continue
		}
		ref := r.Kind + "/" + r.Name
		if r.Namespace != "" {
			ref = r.Kind + "/" + r.Namespace + "/" + r.Name
		}
		drifted = append(drifted, ref)
	}
	return ArgoApp{
		Name:          j.Metadata.Name,
		Sync:          j.Status.Sync.Status,
		Health:        j.Status.Health.Status,
		Automated:     auto,
		SpecErr:       strings.Join(specErrs, " | "),
		OpErr:         opErr,
		Drifted:       drifted,
		SyncErr:       syncErr,
		Project:       j.Spec.Project,
		Resources:     resources,
		DestNamespace: j.Spec.Destination.Namespace,
	}, nil
}

// ── THE Application LIST SHAPE ───────────────────────────────────────────────
//
// AppRef and ParseAppRefList came from internal/extensions/converge. This file
// already owns the Argo classification predicates; the struct those predicates
// describe sat in the extension that happened to parse it first, which meant
// `reachability` imported the whole convergence capability to decode a list.

type AppRef struct {
	Name   string
	Sync   string
	Health string
}

// ParseAppRefList reads `kubectl get applications -o json` into the name +
// sync/health triple. The same anonymous struct and the same append loop were
// written out twice, here and in selectPlatformApps (verify.go) — identical down
// to the field tags.
//
// Deliberately NOT health.ParseArgoApp: that one is richer (spec-error
// conditions, automated-policy detection) and is the right tool where those
// matter. These two callers want only the triple.
func ParseAppRefList(raw []byte) ([]AppRef, error) {
	var doc struct {
		Items []struct {
			Metadata struct {
				Name string `json:"name"`
			} `json:"metadata"`
			Status struct {
				Sync   struct{ Status string } `json:"sync"`
				Health struct{ Status string } `json:"health"`
			} `json:"status"`
		} `json:"items"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, err
	}
	apps := make([]AppRef, 0, len(doc.Items))
	for _, it := range doc.Items {
		apps = append(apps, AppRef{it.Metadata.Name, it.Status.Sync.Status, it.Status.Health.Status})
	}
	return apps, nil
}

func (a AppRef) Healthy() bool { return a.Sync == "Synced" && a.Health == "Healthy" }
