package clusterspec

// derived_values.go — the render-time contract for values `llz render` SYNTHESIZES
// into a per-env patch (HARBOR_HOST, GH_REPO, REGION, OBJ_CLUSTER, …).
//
// The rule this generalizes, learned the expensive way: a derived value must be
// either EMPTY — a deliberate "unset" signal some downstream discovery path is
// written to handle — or WELL-FORMED. It must never be malformed-but-non-empty,
// because that is the one shape nothing catches. `HarborHost` used to concatenate
// "harbor." onto an empty domainSuffix and ship `HARBOR_HOST: "harbor."` to every
// managed instance: non-empty, so it sailed past the provisioner's `host == ""`
// discovery fallback, got seeded into OpenBao as registry_host, and every image
// push and pull 401'd against a registry literally named "harbor.".
//
// That was fixed at its source and again at the consumer, but only for that one
// field. This checks the whole class at render time, so the failure is a local
// `llz render` error naming the field instead of a live cluster misbehaving.
//
// Scanning the RENDERED body rather than the inputs is deliberate: it covers every
// renderer, including ones added later that nobody remembers to wire in here. A
// field with no rule still gets the universal placeholder/whitespace check.

import (
	"fmt"
	"regexp"
	"strings"
)

// placeholderSentinels are the template's own "somebody must fill this" markers.
// One reaching a rendered patch means a substitution silently did not happen.
var placeholderSentinels = []string{"REPLACE_ME", "REPLACE_PER_ENV", "placeholder.example.com"}

// derivedRule is one synthesized env value's shape contract.
//
// EMPTY IS ALWAYS ALLOWED, deliberately. This guard exists for exactly one defect
// — malformed-but-non-empty — and enforcing presence here would be a different
// check in the wrong place. Emptiness is legitimate and load-bearing across these
// fields: HARBOR_HOST is empty by design on Managed App Platform (Linode owns the
// domain, so the spec carries no domainSuffix) and that emptiness is what routes
// the provisioner into Harbor systeminfo discovery; OBJ_CLUSTER is empty whenever
// an env declares no object storage (validate.OBJClusterID("") returns nil on
// purpose). Requiring either would reject valid instances. Spec completeness is
// `llz validate`'s job; shape is this one's.
type derivedRule struct {
	shape func(string) error
	why   string
}

// derivedRules maps the env-var NAME a patch emits to its shape. Keyed by name,
// not by component, so a second renderer emitting GH_REPO inherits the rule.
var derivedRules = map[string]derivedRule{
	"HARBOR_HOST":           {shape: hostShape, why: "a malformed host defeats the provisioner's `== \"\"` discovery fallback and is seeded verbatim as registry_host"},
	"GH_REPO":               {shape: repoSlugShape, why: "the instance's <owner>/<name>; a truncated half makes every gh call target the wrong repo"},
	"REGION":                {shape: tokenShape, why: "the deployment name"},
	"REGION_SHORT":          {shape: tokenShape, why: "the volume-label prefix"},
	"OBJ_CLUSTER":           {shape: tokenShape, why: "the object-storage endpoint id; a wrong one reaches a disjoint bucket namespace"},
	"BROAD_PAT_LABEL":       {shape: tokenShape, why: "selects which PATs the rotator revokes"},
	"BROAD_PAT_DEPLOYMENTS": {shape: tokenShape, why: "selects which deployments receive the rotated PAT"},
}

// envPairRe matches the `- name: FOO` / `value: "BAR"` pair shape the Render*Patch
// helpers emit. Both lines are generated by this package, so the layout is fixed;
// a renderer that ever stops matching simply contributes no pairs, which the
// caller's "found nothing" guard catches rather than silently passing.
var envPairRe = regexp.MustCompile(`(?m)^[ \t]*-[ \t]*name:[ \t]*(\S+)[ \t]*\r?\n[ \t]*value:[ \t]*"([^"]*)"`)

// CheckDerivedEnvValues validates every env value in a rendered per-env patch.
// Returns one error per offending field, so a single render reports all of them
// rather than one per re-run.
func CheckDerivedEnvValues(body string) []error {
	var errs []error
	for _, m := range envPairRe.FindAllStringSubmatch(body, -1) {
		name, value := m[1], m[2]

		// Universal, rule or no rule: a sentinel here means a substitution that was
		// supposed to happen did not.
		for _, s := range placeholderSentinels {
			if strings.Contains(value, s) {
				errs = append(errs, fmt.Errorf("%s is still the placeholder %q — the value was never substituted", name, value))
			}
		}

		if value == "" {
			continue // empty is a deliberate "unset" signal — see derivedRule
		}
		rule, known := derivedRules[name]
		if !known {
			// No declared contract: still reject whitespace damage, which is the
			// other way a value looks present and isn't.
			if strings.TrimSpace(value) != value {
				errs = append(errs, fmt.Errorf("%s has leading/trailing whitespace (%q)", name, value))
			}
			continue
		}
		if err := rule.shape(value); err != nil {
			errs = append(errs, fmt.Errorf("%s is malformed (%q): %v — %s", name, value, err, rule.why))
		}
	}
	return errs
}

// hostShape rejects a hostname with an EMPTY LABEL — a leading or trailing dot, or
// a doubled one. This is the `harbor.` shape precisely: non-empty, obviously wrong,
// and accepted by every `!= ""` check between here and the registry.
func hostShape(v string) error {
	if err := tokenShape(v); err != nil {
		return err
	}
	if strings.HasPrefix(v, ".") || strings.HasSuffix(v, ".") || strings.Contains(v, "..") {
		return fmt.Errorf("empty DNS label")
	}
	return nil
}

// repoSlugShape requires <owner>/<name> with both halves present.
func repoSlugShape(v string) error {
	if err := tokenShape(v); err != nil {
		return err
	}
	owner, name, ok := strings.Cut(v, "/")
	if !ok || owner == "" || name == "" || strings.Contains(name, "/") {
		return fmt.Errorf("not an <owner>/<name> slug")
	}
	return nil
}

// tokenShape is the floor every non-empty derived value must clear.
func tokenShape(v string) error {
	if strings.TrimSpace(v) != v {
		return fmt.Errorf("leading/trailing whitespace")
	}
	if strings.ContainsAny(v, " \t\n") {
		return fmt.Errorf("contains whitespace")
	}
	return nil
}
