package clusterspec

import (
	"regexp"
	"strings"
)

// kustomize.go renders a deployment's manifest/kustomization.yaml — a THIN overlay
// over the shared, DRY manifest tree (so an env is NOT a 30-file clone):
//   - apl-values/_shared/manifest/   always-on base (the platform-support
//                                     AppProject + cluster-foundation), referenced
//                                     under resources:
//   - apl-values/components/<name>/   one kustomize Component per toggleable
//                                     component, referenced under components: when
//                                     spec.components enables it
// The resources live ONCE in those shared dirs; an env carries only this thin
// kustomization + its per-env patch (the volume-labeler REGION_SHORT) + values.yaml.
// Committed because Argo CD syncs git; drift-guarded by `llz render --check`.
// Output is deterministic (registry order) so the check is stable.

const genHeader = `# GENERATED by ` + "`llz render`" + ` from the LandingZone spec — DO NOT EDIT.
# Toggle components via spec.components in environments/<env>.yaml, then re-run
# ` + "`llz render`" + `. See docs/landing-zone-spec.md.
`

const kustomizePreamble = genHeader + `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
`

// hasManifestDir reports whether a component ships a kustomize Component dir under
// apl-values/components/<name>/ (i.e. it delivers raw manifests and/or Argo Apps).
func (c Component) hasManifestDir() bool {
	return len(c.ManifestResources) > 0 || len(c.ArgoApps) > 0
}

// RenderManifestKustomization returns a deployment's manifest/kustomization.yaml: a
// thin overlay listing the shared base under resources: and each ENABLED toggleable
// component's shared Component dir under components: (registry order), plus the
// per-env patches enabled components bring. Mandatory components live in the base,
// so they are not listed here.
func RenderManifestKustomization(components map[string]ComponentToggle) string {
	var dirs []string
	var patches []Patch
	for _, c := range Components {
		if c.Mandatory || !ComponentEnabled(components, c.Name) {
			continue
		}
		if c.hasManifestDir() {
			dirs = append(dirs, c.Name)
		}
		patches = append(patches, c.Patches...)
	}

	var b strings.Builder
	b.WriteString(kustomizePreamble)
	b.WriteString("\nresources:\n  - ../../_shared/manifest\n")
	if len(dirs) > 0 {
		b.WriteString("components:\n")
		for _, d := range dirs {
			b.WriteString("  - ../../components/" + d + "\n")
		}
	}
	if len(patches) > 0 {
		b.WriteString("\npatches:\n")
		for _, p := range patches {
			b.WriteString("  - path: " + p.Path + "\n")
			b.WriteString("    target:\n")
			b.WriteString("      group: " + p.Group + "\n")
			b.WriteString("      version: " + p.Version + "\n")
			b.WriteString("      kind: " + p.Kind + "\n")
			b.WriteString("      name: " + p.Name + "\n")
		}
	}
	return b.String()
}

// RenderEnvRevision returns the per-env env-revision-configmap.yaml — the
// local-config marker the cluster-bootstrap plan-time precondition reads
// (data.revision must equal apps_repo_revision). config.kubernetes.io/local-config
// keeps kustomize from emitting it into any build.
func RenderEnvRevision(revision string) string {
	return "# GENERATED by `llz render` — the git revision this env's in-repo Argo CD\n" +
		"# content tracks (read by cluster-bootstrap; must equal apps_repo_revision).\n" +
		`apiVersion: v1
kind: ConfigMap
metadata:
  name: env-revision
  namespace: argocd
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  revision: ` + revision + "\n"
}

// acmeEmailLine matches the `email:` line(s) in the shared letsencrypt
// ClusterIssuer (both production + staging issuers carry one under spec.acme).
// The shared DNS tree has no other `email:` key, so a line-anchored match is safe.
var acmeEmailLine = regexp.MustCompile(`(?m)^(\s*email:).*$`)

// SetACMEEmail substitutes the Let's Encrypt registration email into the shared
// letsencrypt-clusterissuer.yaml content (spec.acme.email on both ClusterIssuers).
// It is idempotent and re-render-safe: it rewrites whatever value is on each
// `email:` line — the REPLACE_PER_ENV placeholder on first render, or a previously
// rendered address when spec.dns.acmeEmail changes — so the rendered output is a
// pure function of (current file structure, email). The email is instance-wide
// (spec.dns.acmeEmail), so this is rendered ONCE into apl-values/_shared, not per env.
func SetACMEEmail(content, email string) string {
	return acmeEmailLine.ReplaceAllString(content, "${1} "+email)
}

// RenderRegionPatch returns the per-env volume-labeler REGION_SHORT strategic-merge
// patch — the one genuine per-env manifest delta (the rest of the tree is shared).
func RenderRegionPatch(regionShort string) string {
	return "# GENERATED by `llz render` — the per-env REGION_SHORT for the volume labeler.\n" +
		`apiVersion: batch/v1
kind: CronJob
metadata:
  name: linode-volume-labeler
  namespace: llz-linode-volume-labeler
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: relabel
              env:
                - name: REGION_SHORT
                  value: "` + regionShort + "\"\n"
}

// RenderReconcilerEnvPatch returns the per-env strategic-merge patch that fills
// the llz-reconciler Deployment's per-env env — REGION_SHORT, consumed by the
// volume-labels reconciler (the only genuine per-env delta for the otherwise
// shared reconciler tree). Emitted whenever the (default-on) llzReconciler
// component is enabled; harmless when volume-labels is off (unread env).
func RenderReconcilerEnvPatch(regionShort string) string {
	return "# GENERATED by `llz render` — the per-env REGION_SHORT for the llz reconciler.\n" +
		`apiVersion: apps/v1
kind: Deployment
metadata:
  name: llz-reconciler
  namespace: llz-reconciler
spec:
  template:
    spec:
      containers:
        - name: reconcile
          env:
            - name: REGION_SHORT
              value: "` + regionShort + "\"\n"
}

// RenderHarborHostPatch returns the per-env HARBOR_HOST strategic-merge patch
// for the harbor-robot-provisioner CronJob (components/harbor/): the registry
// host written into OpenBao as registry_host, derived as
// harbor.<cluster.bootstrap.domainSuffix> — the same derivation `llz ci
// resolve-harbor-url` uses. Instances overriding the HARBOR_URL repo var must
// keep this in step.
func RenderHarborHostPatch(domainSuffix string) string {
	return "# GENERATED by `llz render` — the per-env HARBOR_HOST for the harbor robot provisioner.\n" +
		`apiVersion: batch/v1
kind: CronJob
metadata:
  name: harbor-robot-provisioner
  namespace: harbor
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: provision
              env:
                - name: HARBOR_HOST
                  value: "harbor.` + domainSuffix + "\"\n"
}

// RenderOtelSANPatch returns the per-env dnsNames patch for the OTel Collector
// serving Certificate (components/observability/otel-bootstrap-ca.yaml): the
// env-shaped otel.<env>.internal SAN plus the static Service SANs. kustomize
// treats CR lists as atomic, so this replaces spec.dnsNames wholesale — the
// patch must carry the COMPLETE list, not just the env entry. SANs preserved
// verbatim from the retired `llz ci gen-bootstrap-tls` workflow step.
func RenderOtelSANPatch(env string) string {
	return "# GENERATED by `llz render` — the per-env otel.<env>.internal SAN for the OTel\n" +
		"# Collector serving cert (replaces spec.dnsNames wholesale; CR lists are atomic).\n" +
		`apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-otel-collector-tls
  namespace: llz-observability
spec:
  dnsNames:
    - otel.` + env + `.internal
    - platform-otel-collector.llz-observability.svc
    - platform-otel-collector.llz-observability.svc.cluster.local
`
}

// RenderRotatorEnvPatch returns the per-env REGION + OBJ_CLUSTER strategic-merge
// patch for the Linode credential rotator CronJob (region = deployment name,
// objCluster = the spec's object-storage cluster). Emitted by `llz render` when
// the linodeCredRotator component is enabled.
func RenderRotatorEnvPatch(region, objCluster string) string {
	return "# GENERATED by `llz render` — per-env REGION + OBJ_CLUSTER for the Linode credential rotator.\n" +
		`apiVersion: batch/v1
kind: CronJob
metadata:
  name: linode-cred-rotator
  namespace: llz-linode-cred-rotator
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rotate
              env:
                - name: REGION
                  value: "` + region + `"
                - name: OBJ_CLUSTER
                  value: "` + objCluster + "\"\n"
}
