package clusterspec

import (
	"strconv"
	"strings"
)

// kustomize.go renders a deployment's manifest/kustomization.yaml — a THIN overlay
// over the shared, DRY manifest tree that lives at the REPO ROOT, OUTSIDE the
// instance template (so an instance vendors none of it — see platform-apl/):
//   - platform-apl/manifest/         always-on base (the platform-support
//                                     AppProject + cluster-foundation), referenced
//                                     under resources:
//   - platform-apl/components/<name>/ one kustomize Component per toggleable
//                                     component, referenced under components: when
//                                     spec.components enables it
// The resources live ONCE in those shared dirs; an env carries only this thin
// kustomization + its per-env patch (the volume-labeler REGION_SHORT) + values.yaml.
// Committed because Argo CD syncs git; drift-guarded by `llz render --check`.
// Output is deterministic (registry order) so the check is stable.

const genHeader = `# GENERATED by ` + "`llz render`" + ` from the LandingZone spec — DO NOT EDIT.
# Toggle components via spec.components in environments/<env>.yaml, then re-run
# ` + "`llz render`" + `. See docs/landing-zone-spec.md.
`

// remoteBasePrefix is the kustomize remote-ref base for the SHARED platform-apl tree
// hosted at the repo root of the (public) template repo. The manifest layer is
// byte-identical across instances (see docs/designs/apl-values-remote-refs.md), so an
// instance references it from the template repo at a pinned ref instead of vendoring
// ~4k lines — the tree lives at platform-apl/ (repo root), NOT under instance-template,
// so copier never scaffolds it into an instance and there is nothing to prune. ArgoCD's
// repo-server fetches it transitively when it builds the instance-repo App — the same
// egress it already uses to pull the cluster-foundation OCI chart from ghcr.io. There
// are no private forks, so the org is a constant (see the upstream_org hardcoding).
const remoteBasePrefix = "github.com/akamai-consulting/lke-landing-zone//platform-apl/"

// remoteFetchTimeout overrides kustomize's git-loader default (27s), which is too short
// for ArgoCD's repo-server to clone the ~35MB template repo (anonymous, arbitrary-SHA) —
// the e2e hit exactly that 27s cap. kustomize takes the override as a per-URL `?timeout=`
// query param (kubernetes-sigs/kustomize#3742; no env var exists). 80s gives ~3x headroom
// while staying under the repo-server's own ARGOCD_EXEC_TIMEOUT (default 90s), which caps
// total build time; ArgoCD caches the clone after the first fetch, so later syncs are fast.
const remoteFetchTimeout = "80"

// RemoteBase returns the pinned remote-ref URL for a path under the shared apl-values
// tree (e.g. relPath "components/openbao"), fetched from the template repo at ref with a
// bumped git-fetch timeout. ref is the template version the instance tracks (llz_version
// tag, or the SHA under test in e2e) — resolved by the command layer, never read here
// (clusterspec stays pure).
func RemoteBase(relPath, ref string) string {
	return remoteBasePrefix + relPath + "?ref=" + ref + "&timeout=" + remoteFetchTimeout
}

// componentRef returns the kustomize reference for an enabled component's shared dir:
// a pinned remote-ref URL (the normal instance path — every component tree at
// platform-apl/components/ is token-free), or the LOCAL relative path (localRel, e.g.
// "../../../../platform-apl/components/") only when ref is empty (the no-version
// drift-check / unit-test context; instances always resolve a ref).
func componentRef(name, localRel, ref string) string {
	if ref == "" {
		return localRel + name
	}
	return RemoteBase("components/"+name, ref)
}

const kustomizePreamble = genHeader + `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
`

// hasManifestDir reports whether a component ships a kustomize Component dir under
// platform-apl/components/<name>/ (i.e. it delivers raw manifests and/or Argo Apps).
func (c Component) hasManifestDir() bool {
	return len(c.ManifestResources) > 0 || len(c.ArgoApps) > 0
}

// RenderManifestKustomization returns a deployment's manifest/kustomization.yaml: a
// thin overlay over the shared base. It lists, in registry order:
//   - resources: the shared _shared/manifest base + one health-inert Application CR
//     per ENABLED carved component (blast-radius isolation — see CarvedApp);
//   - components: each ENABLED plain (non-carved) component's shared Component dir;
//   - patches: the per-env patches plain components bring (a carved component's
//     patches move into its own apps/<name>/ source root, not here).
//
// Mandatory components live in the base, so they are not listed here.
//
// ref is the template ref the instance tracks (llz_version / e2e SHA). When non-empty,
// each token-free component is referenced from the template repo at that ref instead of
// vendored locally; an empty ref keeps every reference local (the drift-check default and
// any context without an instance version). See RemoteBase / componentRef.
// sharedManifestRef returns the reference for the always-on platform-apl/manifest base:
// the pinned remote-ref URL when a template ref is resolved, else the local relative
// path (repo-root platform-apl/, four levels up from an env's manifest/ overlay — the
// no-version drift-check / test context only). The per-instance instance-custom
// Application is NOT part of this base (it carries the instance repo) —
// RenderManifestKustomization adds it as a local resource.
func sharedManifestRef(ref string) string {
	if ref == "" {
		return "../../../../platform-apl/manifest"
	}
	return RemoteBase("manifest", ref)
}

// clusterHealthWorkflowName / clusterHealthWorkflowTemplate identify the Argo
// WorkflowTemplate whose container image the kustomize images: transformer cannot
// reach (a CRD field) — so RenderManifestKustomization retags it with a JSON6902
// patch instead, letting the component tree ship a token-free :latest base ref.
const (
	clusterHealthWorkflowName     = "clusterHealthWorkflow"
	clusterHealthWorkflowTemplate = "llz-cluster-health"
)

func RenderManifestKustomization(components map[string]ComponentToggle, ref, acmeEmail, imageTag string) string {
	var dirs []string       // plain component dirs, referenced under components:
	var carvedApps []string // carved App CR filenames, referenced under resources:
	var patches []Patch     // patches from plain components only
	for _, c := range Components {
		if c.Mandatory || !ComponentEnabled(components, c.Name) {
			continue
		}
		if c.CarvedApp != nil {
			carvedApps = append(carvedApps, c.CarvedApp.AppName+".yaml")
			continue
		}
		if c.hasManifestDir() {
			dirs = append(dirs, c.Name)
		}
		patches = append(patches, c.Patches...)
	}

	var b strings.Builder
	b.WriteString(kustomizePreamble)
	// The shared base (remote when pinned) + the per-instance instance-custom App
	// (local, render-emitted with this instance's repo — NOT in the shared base) +
	// one health-inert App CR per enabled carved component.
	b.WriteString("\nresources:\n  - " + sharedManifestRef(ref) + "\n")
	b.WriteString("  - instance-custom.yaml\n")
	for _, a := range carvedApps {
		b.WriteString("  - " + a + "\n")
	}
	if len(dirs) > 0 {
		b.WriteString("components:\n")
		for _, d := range dirs {
			b.WriteString("  - " + componentRef(d, "../../../../platform-apl/components/", ref) + "\n")
		}
	}
	// clusterHealthWorkflow's llz image lives in an Argo WorkflowTemplate (a CRD the
	// images: transformer can't retag), so — now that its component ships a token-free
	// :latest base — retag it here with a JSON6902 patch when it's enabled and this
	// instance/e2e resolved an image tag.
	retagHealth := imageTag != "" && ComponentEnabled(components, clusterHealthWorkflowName)
	if len(patches) > 0 || acmeEmail != "" || retagHealth {
		b.WriteString("\npatches:\n")
		for _, p := range patches {
			b.WriteString("  - path: " + p.Path + "\n")
			b.WriteString("    target:\n")
			b.WriteString("      group: " + p.Group + "\n")
			b.WriteString("      version: " + p.Version + "\n")
			b.WriteString("      kind: " + p.Kind + "\n")
			b.WriteString("      name: " + p.Name + "\n")
		}
		// Instance-wide ACME contact: the shared letsencrypt ClusterIssuers ship
		// email: "" (a valid contact-less registration); when spec.dns.acmeEmail is
		// set, patch it onto BOTH issuers in place (target by kind — no per-name
		// entry). This replaces the former file-rewrite, which can't reach the now-
		// remote dns tree. Unset → no patch (email: "" stands).
		if acmeEmail != "" {
			b.WriteString("  - target:\n      group: cert-manager.io\n      kind: ClusterIssuer\n")
			b.WriteString("    patch: |-\n      - op: replace\n        path: /spec/acme/email\n        value: " + acmeEmail + "\n")
		}
		// Retag the health WorkflowTemplate's container image (a CRD field the images:
		// transformer can't reach) to this instance/e2e llz image.
		if retagHealth {
			b.WriteString("  - target:\n      group: argoproj.io\n      version: v1alpha1\n      kind: WorkflowTemplate\n      name: " + clusterHealthWorkflowTemplate + "\n")
			b.WriteString("    patch: |-\n      - op: replace\n        path: /spec/templates/0/container/image\n        value: " + llzImageName + ":" + imageTag + "\n")
		}
	}
	return b.String()
}

// RenderInstanceCustomApp returns the per-instance instance-custom Argo Application —
// the operator escape hatch (wave 10, prune:false) that syncs the instance's own
// apl-values/_shared/custom/ tree. It carries the instance's values-repo URL, so it is
// render-emitted LOCALLY into the overlay rather than vendored in the shared base (which
// is fetched remotely and must be byte-identical across instances). Its AppProject
// (instance-custom-project.yaml, no per-instance data) stays in the shared base.
func RenderInstanceCustomApp(repoURL string) string {
	return genHeader + `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instance-custom
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  revisionHistoryLimit: 3
  project: instance-custom
  source:
    repoURL: ` + repoURL + `
    path: apl-values/_shared/custom
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - CreateNamespace=false
`
}

// RenderCarvedApp returns the Argo CD Application CR for a carved component in env
// — a git-path App (project platform-bootstrap, same as llz-secret-store) pointing
// at the self-contained per-env source root apps/<name>/ (RenderCarvedAppKustomization).
// The App CR itself is health-inert (Argo assesses no Application health without an
// explicit customization, which apl-core does not configure — see the wave-health
// guard), so platform-bootstrap stays Synced/Healthy while the App health-gates its
// OWN content: a Degraded resource fails only this App. repoURL + revision pin the
// same instance repo + apps_repo_revision the platform-bootstrap Application uses.
func RenderCarvedApp(c Component, env, repoURL, revision string) string {
	ca := c.CarvedApp
	return genHeader + `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ` + ca.AppName + `
  namespace: argocd
  annotations:
    # App-level wave: the floor for this App's content, ordered against the other
    # carved Apps (externalSecrets lowest). See clusterspec CarvedApp.AppWave.
    argocd.argoproj.io/sync-wave: "` + strconv.Itoa(ca.AppWave) + `"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  revisionHistoryLimit: 3
  project: platform-bootstrap
  source:
    repoURL: ` + repoURL + `
    targetRevision: ` + revision + `
    path: apl-values/` + env + `/apps/` + c.Name + `
  destination:
    server: https://kubernetes.default.svc
    namespace: ` + ca.Namespace + `
  syncPolicy:
    automated:
      # prune + selfHeal mirror platform-bootstrap: the carved content stays in
      # lockstep with git, but a transient empty render can't cascade (SSA below).
      prune: true
      selfHeal: true
    retry:
      # Same ~1h first-boot budget as platform-bootstrap: wave-5 ExternalSecrets
      # wait on the out-of-band OpenBao unseal -> eso role -> store Ready chain.
      limit: 40
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 90s
    syncOptions:
      - ServerSideApply=true
      # The bundle may carry a CR whose CRD another App installs (ExternalSecret,
      # ServiceMonitor); don't abort the sync dry-running a not-yet-registered kind.
      - SkipDryRunOnMissingResource=true
      # cluster-foundation (wave -20) owns the namespaces; don't create/own them here.
      - CreateNamespace=false
`
}

// RenderCarvedAppKustomization returns the apps/<name>/kustomization.yaml a carved
// App syncs: it pulls in the shared kustomize Component (which lives ONCE under
// platform-apl/components/<name>/, three levels up) and applies this env's patches —
// a complete, env-correct source root for the App. The patch files sit alongside
// this kustomization (RenderReconcilerEnvPatch et al., written by `llz render`).
// llzImageName is the constant in-cluster llz image (no forks → constant org); a
// carved app's images: transformer overrides its tag per instance/e2e so the shared
// component ships a plain `:latest` reference and carries no copier token.
const llzImageName = "ghcr.io/akamai-consulting/llz"

// carvedLLZImageComponents are the carved components whose workload runs the llz
// image via a kustomize-overridable field (Deployment/CronJob container) — the
// images: transformer retags it. clusterHealthWorkflow is absent here because it is
// a PLAIN (non-carved) component AND its image sits in an Argo WorkflowTemplate that
// the images: transformer can't reach — RenderManifestKustomization retags it with a
// JSON6902 patch instead (see retagHealth).
var carvedLLZImageComponents = map[string]bool{"llzReconciler": true, "harbor": true}

func RenderCarvedAppKustomization(c Component, ref, imageTag string) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString(`apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ` + componentRef(c.Name, "../../../../../platform-apl/components/", ref) + "\n")
	// Retag the llz image for this instance (release tag) or e2e (sha image); the
	// shared component ships `:latest`. Only for components whose image is a plain
	// container field the transformer can reach.
	if imageTag != "" && carvedLLZImageComponents[c.Name] {
		b.WriteString("images:\n  - name: " + llzImageName + "\n    newTag: " + imageTag + "\n")
	}
	if len(c.Patches) > 0 {
		b.WriteString("patches:\n")
		for _, p := range c.Patches {
			b.WriteString("  - path: " + p.Path + "\n")
			b.WriteString("    target:\n")
			b.WriteString("      group: " + p.Group + "\n")
			b.WriteString("      version: " + p.Version + "\n")
			b.WriteString("      kind: " + p.Kind + "\n")
			b.WriteString("      name: " + p.Name + "\n")
		}
	}
	return b.String()
}

// RenderEnvRevision returns the per-env env-revision-configmap.yaml — the
// local-config marker the cluster-bootstrap plan-time precondition reads
// (data.revision must equal apps_repo_revision). config.kubernetes.io/local-config
// keeps kustomize from emitting it into any build.
func RenderEnvRevision(revision string) string {
	return "# GENERATED by `llz render` — the git revision this env's in-repo Argo CD\n" +
		"# content tracks (read by cluster-bootstrap; must equal apps_repo_revision).\n" +
		`apiVersion: v1
kind: ConfigMap
metadata:
  name: env-revision
  namespace: argocd
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  revision: ` + revision + "\n"
}

// RenderReconcilerEnvPatch returns the per-env strategic-merge patch that fills
// the llz-reconciler Deployment's per-env env — REGION_SHORT, consumed by the
// volume-labels reconciler (the only genuine per-env delta for the otherwise
// shared reconciler tree). Emitted whenever the (default-on) llzReconciler
// component is enabled; harmless when volume-labels is off (unread env).
func RenderReconcilerEnvPatch(regionShort, region, objCluster string) string {
	return "# GENERATED by `llz render` — the per-env REGION_SHORT (volume-labels) +\n" +
		"# REGION/OBJ_CLUSTER (linode-creds) for the llz reconciler.\n" +
		`apiVersion: apps/v1
kind: Deployment
metadata:
  name: llz-reconciler
  namespace: llz-reconciler
spec:
  template:
    spec:
      containers:
        - name: reconcile
          env:
            - name: REGION_SHORT
              value: "` + regionShort + `"
            - name: REGION
              value: "` + region + `"
            - name: OBJ_CLUSTER
              value: "` + objCluster + "\"\n"
}

// RenderHarborHostPatch returns the per-env strategic-merge patch for the
// harbor-robot-provisioner CronJob (components/harbor/). It fills the two
// per-instance env values that let components/harbor be a token-free remote base:
//   - HARBOR_HOST: the registry host written into OpenBao as registry_host, derived
//     as harbor.<cluster.bootstrap.domainSuffix> — the same derivation `llz ci
//     resolve-harbor-url` uses. Instances overriding the HARBOR_URL repo var must
//     keep this in step.
//   - GH_REPO: the instance's own <owner>/<name> (this env's values-repo slug) — the
//     repo-secret publication target the standby bootstrap reads.
// env is a keyed list (mergeKey name), so these merge onto the component's other
// env entries by name. The container image is retagged separately by the carved
// app's images: transformer (llzImageName), not here.
func RenderHarborHostPatch(domainSuffix, ghRepo string) string {
	return "# GENERATED by `llz render` — the per-env HARBOR_HOST + GH_REPO for the harbor robot provisioner.\n" +
		`apiVersion: batch/v1
kind: CronJob
metadata:
  name: harbor-robot-provisioner
  namespace: harbor
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: provision
              env:
                - name: HARBOR_HOST
                  value: "harbor.` + domainSuffix + `"
                - name: GH_REPO
                  value: "` + ghRepo + "\"\n"
}

// RenderBroadPATEnvPatch returns the per-env strategic-merge patch that fills the
// broad-pat-rotator CronJob's account-wide BROAD_PAT_LABEL (the Linode label of
// the broad PAT family this deployment rotates) and BROAD_PAT_DEPLOYMENTS (the
// space-separated infra-<d> environments whose LINODE_API_TOKEN secret gets the
// new value) — the base cronjob.yaml (components/broadPatRotator/) ships REPLACE_ME
// for both. Env entries merge by name, so this replaces the placeholders in place.
// Emitted whenever the (default-disabled) broadPatRotator component is enabled;
// Validate requires both values are set, so neither is ever the empty string here.
func RenderBroadPATEnvPatch(label, deployments string) string {
	return "# GENERATED by `llz render` — the account-wide BROAD_PAT_LABEL + BROAD_PAT_DEPLOYMENTS\n" +
		"# for the broad Linode PAT rotator (from spec.components.broadPatRotator).\n" +
		`apiVersion: batch/v1
kind: CronJob
metadata:
  name: broad-pat-rotator
  namespace: llz-pat-rotator
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rotate
              env:
                - name: BROAD_PAT_LABEL
                  value: "` + label + `"
                - name: BROAD_PAT_DEPLOYMENTS
                  value: "` + deployments + "\"\n"
}

// RenderOtelSANPatch returns the per-env dnsNames patch for the OTel Collector
// serving Certificate (components/observability/otel-bootstrap-ca.yaml): the
// env-shaped otel.<env>.internal SAN plus the static Service SANs. kustomize
// treats CR lists as atomic, so this replaces spec.dnsNames wholesale — the
// patch must carry the COMPLETE list, not just the env entry. SANs preserved
// verbatim from the retired `llz ci gen-bootstrap-tls` workflow step.
func RenderOtelSANPatch(env string) string {
	return "# GENERATED by `llz render` — the per-env otel.<env>.internal SAN for the OTel\n" +
		"# Collector serving cert (replaces spec.dnsNames wholesale; CR lists are atomic).\n" +
		`apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-otel-collector-tls
  namespace: llz-observability
spec:
  dnsNames:
    - otel.` + env + `.internal
    - platform-otel-collector.llz-observability.svc
    - platform-otel-collector.llz-observability.svc.cluster.local
`
}
