package clusterspec

import (
	"strings"
	"testing"
)

// allOn is the default component set (every component enabled except DefaultDisabled).
func allOn() map[string]ComponentToggle {
	m := map[string]ComponentToggle{}
	for _, c := range Components {
		m[c.Name] = ComponentToggle{Enabled: boolPtr(!c.DefaultDisabled)}
	}
	return m
}

func TestRenderManifestKustomization(t *testing.T) {
	out := RenderManifestKustomization(allOn(), "", "", "")
	// Thin overlay: the shared base + a health-inert Application CR under resources:
	// for each enabled CARVED component (blast-radius decomposition) + a components:
	// list of the remaining plain component dirs.
	for _, want := range []string{
		"GENERATED by", "kind: Kustomization",
		"- ../../../../platform-apl/manifest",
		// carved components → App CRs under resources:, NOT components: dirs
		"- llz-externalsecrets.yaml",
		"- llz-observability.yaml",
		"- llz-harbor.yaml",
		"- llz-reconciler.yaml",
		// plain (non-carved) components stay as components: dirs
		"- ../../../../platform-apl/components/openbao",
		"- ../../../../platform-apl/components/certManager",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("thin overlay missing %q:\n%s", want, out)
		}
	}
	// Carved components no longer appear as components: dirs, and their per-env
	// patches move into their own App source root — so the manifest overlay carries
	// NO patches: section (every patch-bearing component is carved).
	for _, absent := range []string{
		"- ../../../../platform-apl/components/externalSecrets",
		"- ../../../../platform-apl/components/observability",
		"- ../../../../platform-apl/components/harbor",
		"- ../../../../platform-apl/components/llzReconciler",
		"patches:", "llz-reconciler-env-patch.yaml",
	} {
		if strings.Contains(out, absent) {
			t.Errorf("carved component leaked %q into the manifest overlay:\n%s", absent, out)
		}
	}
	// Mandatory components (argocd, clusterFoundation) live in the base — never in
	// the components: list.
	if strings.Contains(out, "components/argocd") || strings.Contains(out, "components/clusterFoundation") {
		t.Errorf("mandatory components must not be listed (they're in the base):\n%s", out)
	}
	// Disabling harbor drops its carved App CR (and only it).
	off := allOn()
	off["harbor"] = ComponentToggle{Enabled: boolPtr(false)}
	dropped := RenderManifestKustomization(off, "", "", "")
	if strings.Contains(dropped, "llz-harbor.yaml") {
		t.Error("disabled harbor should drop its carved App CR")
	}
	if !strings.Contains(dropped, "llz-observability.yaml") {
		t.Error("disabling harbor must not drop sibling carved Apps")
	}
}

func TestRenderManifestKustomization_RemoteRefs(t *testing.T) {
	const ref = "v9.9.9"
	out := RenderManifestKustomization(allOn(), ref, "", "")
	// Token-free plain components are fetched from the template repo at the pinned ref.
	for _, want := range []string{
		"- github.com/akamai-consulting/lke-landing-zone//platform-apl/components/openbao?ref=v9.9.9&timeout=80",
		"- github.com/akamai-consulting/lke-landing-zone//platform-apl/components/certManager?ref=v9.9.9&timeout=80",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("remote ref missing %q:\n%s", want, out)
		}
	}
	// The git-fetch timeout override (kustomize's 27s default is too short for the
	// ~35MB repo) must ride every remote ref.
	if strings.Contains(out, "?ref=v9.9.9\n") || !strings.Contains(out, "&timeout=80") {
		t.Errorf("every remote ref must carry &timeout=80:\n%s", out)
	}
	// The shared _shared/manifest base is fetched remotely too (Phase 1); its per-
	// instance instance-custom ApplicationSet is split OUT and stays a local resource.
	if !strings.Contains(out, "- github.com/akamai-consulting/lke-landing-zone//platform-apl/manifest?ref=v9.9.9") {
		t.Errorf("shared base should be a remote ref:\n%s", out)
	}
	if !strings.Contains(out, "- instance-custom.yaml") {
		t.Errorf("instance-custom ApplicationSet must stay a local resource:\n%s", out)
	}
	// An empty ref keeps everything local (drift-check default / no instance context).
	local := RenderManifestKustomization(allOn(), "", "", "")
	if strings.Contains(local, "github.com/akamai-consulting") {
		t.Errorf("empty ref must stay fully local:\n%s", local)
	}
	if !strings.Contains(local, "- ../../../../platform-apl/manifest") || !strings.Contains(local, "- ../../../../platform-apl/components/openbao") {
		t.Errorf("empty ref should reference the base + components locally:\n%s", local)
	}
	// spec.dns.acmeEmail set → an inline ClusterIssuer patch carries the contact
	// (the shared dns tree ships email: "" and is now remote, so it can't be rewritten).
	withEmail := RenderManifestKustomization(allOn(), ref, "ops@example.com", "")
	for _, want := range []string{"kind: ClusterIssuer", "path: /spec/acme/email", "value: ops@example.com"} {
		if !strings.Contains(withEmail, want) {
			t.Errorf("acmeEmail patch missing %q:\n%s", want, withEmail)
		}
	}
	if strings.Contains(out, "/spec/acme/email") {
		t.Errorf("unset acmeEmail must emit no ClusterIssuer patch:\n%s", out)
	}
}

func TestRenderCarvedAppKustomization_RemoteRefs(t *testing.T) {
	const ref = "v9.9.9"
	// A token-free carved component (observability) is fetched remotely at the ref.
	obs, _ := LookupComponent("observability")
	if got := RenderCarvedAppKustomization(obs, ref, ""); !strings.Contains(got,
		"- github.com/akamai-consulting/lke-landing-zone//platform-apl/components/observability?ref=v9.9.9") {
		t.Errorf("observability carved kustomization should reference the remote ref:\n%s", got)
	}
	// llzReconciler is remote (Phase 0 moved its image to an images: transformer), and
	// with an imageTag set the carved kustomization retags the shared :latest image.
	rec, _ := LookupComponent("llzReconciler")
	got := RenderCarvedAppKustomization(rec, ref, "sha-abc123")
	if !strings.Contains(got, "components/llzReconciler?ref=v9.9.9") {
		t.Errorf("llzReconciler should be a remote ref now:\n%s", got)
	}
	for _, want := range []string{"images:", "name: ghcr.io/akamai-consulting/llz", "newTag: sha-abc123"} {
		if !strings.Contains(got, want) {
			t.Errorf("llzReconciler carved kustomization missing image retag %q:\n%s", want, got)
		}
	}
	// A component that doesn't run the llz image (observability) gets no images: block.
	if strings.Contains(RenderCarvedAppKustomization(obs, ref, "sha-abc123"), "images:") {
		t.Errorf("observability should not get an llz images: transformer")
	}
}

// clusterHealthWorkflow is a PLAIN (non-carved) component fetched remotely from
// platform-apl; its Argo WorkflowTemplate image (a CRD the images: transformer can't
// reach) is retagged by a JSON6902 patch in the manifest overlay when it's enabled
// and an image tag is resolved.
func TestRenderManifestKustomization_HealthWorkflowRetag(t *testing.T) {
	comps := allOn()
	comps["clusterHealthWorkflow"] = ComponentToggle{Enabled: boolPtr(true)}
	out := RenderManifestKustomization(comps, "v9.9.9", "", "sha-abc123")
	for _, want := range []string{
		"- github.com/akamai-consulting/lke-landing-zone//platform-apl/components/clusterHealthWorkflow?ref=v9.9.9",
		"kind: WorkflowTemplate",
		"name: llz-cluster-health",
		"path: /spec/templates/0/container/image",
		"value: ghcr.io/akamai-consulting/llz:sha-abc123",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("health retag missing %q:\n%s", want, out)
		}
	}
	// No image tag → no retag patch (the component still ships :latest remotely).
	if noTag := RenderManifestKustomization(comps, "v9.9.9", "", ""); strings.Contains(noTag, "/spec/templates/0/container/image") {
		t.Errorf("no imageTag must emit no WorkflowTemplate retag:\n%s", noTag)
	}
	// Disabled → no retag even with an image tag.
	off := allOn()
	off["clusterHealthWorkflow"] = ComponentToggle{Enabled: boolPtr(false)}
	if strings.Contains(RenderManifestKustomization(off, "v9.9.9", "", "sha-abc123"), "WorkflowTemplate") {
		t.Error("disabled clusterHealthWorkflow must emit no retag patch")
	}
}

func TestRenderInstanceCustom(t *testing.T) {
	app := RenderInstanceCustom("https://github.com/acme/inst.git", "v1.2.3")
	for _, want := range []string{
		"kind: ApplicationSet",
		"name: instance-custom",
		"project: instance-custom",
		"repoURL: https://github.com/acme/inst.git",
		`argocd.argoproj.io/sync-wave: "10"`,
		"prune: false", // operator content is theirs to delete deliberately
		"GENERATED by",
		// App Platform's GitOps layout: one App per namespaces/<ns>/ dir + one global.
		"- path: apl-values/_shared/custom/namespaces/*",
		"- path: apl-values/_shared/custom/global",
		"name: instance-custom-{{.path.basename}}",
		"namespace: '{{.path.basename}}'",
		"goTemplate: true",
		"CreateNamespace=true",
		// Removing a dir from git must orphan resources, never cascade-delete them.
		"preserveResourcesOnDeletion: true",
	} {
		if !strings.Contains(app, want) {
			t.Errorf("instance-custom ApplicationSet missing %q:\n%s", want, app)
		}
	}
	// The generated Apps must NOT carry a resources finalizer — that is what
	// preserveResourcesOnDeletion buys, and a finalizer would defeat prune:false by
	// tearing down workloads when a directory disappears from git.
	if strings.Contains(app, "resources-finalizer.argocd.argoproj.io") {
		t.Errorf("generated Apps must not carry a resources finalizer:\n%s", app)
	}
	// The escape hatch pins to the instance's apps_repo_revision, like every other
	// rendered App. It used to hardcode HEAD, leaving custom/ floating on a pinned
	// instance — the regression this asserts against.
	if strings.Count(app, "targetRevision: v1.2.3")+strings.Count(app, "revision: v1.2.3") != 3 {
		t.Errorf("revision must pin both generators + the App template:\n%s", app)
	}
	if strings.Contains(app, "HEAD") {
		t.Errorf("a pinned instance must not float on HEAD:\n%s", app)
	}
	// Unpinned instances keep the old default.
	if !strings.Contains(RenderInstanceCustom("https://github.com/acme/inst.git", ""), "revision: HEAD") {
		t.Error("empty revision should fall back to HEAD")
	}
	// The repo is substituted verbatim.
	if !strings.Contains(RenderInstanceCustom("https://github.com/other/repo.git", "main"), "repoURL: https://github.com/other/repo.git") {
		t.Error("repoURL should be substituted verbatim")
	}
}

func TestRenderCarvedApp(t *testing.T) {
	es, _ := LookupComponent("externalSecrets")
	app := RenderCarvedApp(es, "prod", "https://github.com/acme/inst.git", "v1.2.3")
	for _, want := range []string{
		"kind: Application",
		"name: llz-externalsecrets",
		"project: platform-bootstrap",
		`argocd.argoproj.io/sync-wave: "-10"`, // externalSecrets is the dependency root → lowest
		"repoURL: https://github.com/acme/inst.git",
		"targetRevision: v1.2.3",
		"path: apl-values/prod/apps/externalSecrets",
		"namespace: external-secrets",
		"SkipDryRunOnMissingResource=true",
	} {
		if !strings.Contains(app, want) {
			t.Errorf("carved App CR missing %q:\n%s", want, app)
		}
	}
	// externalSecrets (dependency root) must carry a strictly lower App wave than
	// every consumer App — the ordering the wave-dependency-guard enforces.
	esWave := es.CarvedApp.AppWave
	for _, name := range []string{"observability", "harbor", "llzReconciler"} {
		c, _ := LookupComponent(name)
		if c.CarvedApp == nil {
			t.Fatalf("%s should be carved", name)
		}
		if esWave >= c.CarvedApp.AppWave {
			t.Errorf("externalSecrets App wave %d must be < %s App wave %d", esWave, name, c.CarvedApp.AppWave)
		}
	}
}

func TestRenderCarvedAppKustomization(t *testing.T) {
	// A carved component WITH a patch (observability) references the shared Component
	// three levels up + its env patch.
	obs, _ := LookupComponent("observability")
	k := RenderCarvedAppKustomization(obs, "", "")
	for _, want := range []string{
		"kind: Kustomization",
		"- ../../../../../platform-apl/components/observability",
		"patches:",
		"path: otel-collector-tls-san-patch.yaml",
		"kind: Certificate",
	} {
		if !strings.Contains(k, want) {
			t.Errorf("carved App kustomization missing %q:\n%s", want, k)
		}
	}
	// A carved component WITHOUT a patch (externalSecrets) omits the patches: section.
	es, _ := LookupComponent("externalSecrets")
	if got := RenderCarvedAppKustomization(es, "", ""); strings.Contains(got, "patches:") {
		t.Errorf("patch-less carved component should omit patches::\n%s", got)
	}
}

func TestBroadPatRotator_CarvedAndPatched(t *testing.T) {
	c, ok := LookupComponent("broadPatRotator")
	if !ok {
		t.Fatal("broadPatRotator component missing")
	}
	// It carves into its own health-inert App (blast-radius isolation) and brings a
	// per-env env patch — the same shape as harbor/reconciler.
	if c.CarvedApp == nil {
		t.Fatal("broadPatRotator should be carved (own namespace + account:read_write PAT)")
	}
	if c.CarvedApp.Namespace != "llz-pat-rotator" {
		t.Errorf("carved App namespace = %q, want llz-pat-rotator", c.CarvedApp.Namespace)
	}
	if len(c.Patches) != 1 || c.Patches[0].Path != "broad-pat-rotator-env-patch.yaml" || c.Patches[0].Kind != "CronJob" {
		t.Errorf("broadPatRotator should carry the CronJob env patch; got %+v", c.Patches)
	}
	// externalSecrets (dep root) must floor below it, like every other consumer App.
	es, _ := LookupComponent("externalSecrets")
	if es.CarvedApp.AppWave >= c.CarvedApp.AppWave {
		t.Errorf("externalSecrets wave %d must be < broadPatRotator wave %d", es.CarvedApp.AppWave, c.CarvedApp.AppWave)
	}
	// The carved App kustomization pulls the shared Component + references the patch.
	k := RenderCarvedAppKustomization(c, "", "")
	for _, want := range []string{"../../../../../platform-apl/components/broadPatRotator", "path: broad-pat-rotator-env-patch.yaml", "kind: CronJob"} {
		if !strings.Contains(k, want) {
			t.Errorf("carved kustomization missing %q:\n%s", want, k)
		}
	}
}

func TestRenderBroadPATEnvPatch(t *testing.T) {
	p := RenderBroadPATEnvPatch("gha-acme_LINODE_API_TOKEN", "prod e2e", "akamai-consulting/lke-landing-zone-example")
	for _, want := range []string{
		"kind: CronJob",
		"name: broad-pat-rotator",
		"namespace: llz-pat-rotator",
		"- name: rotate",
		`- name: BROAD_PAT_LABEL`,
		`value: "gha-acme_LINODE_API_TOKEN"`,
		`- name: BROAD_PAT_DEPLOYMENTS`,
		`value: "prod e2e"`,
		`- name: GH_REPO`,
		`value: "akamai-consulting/lke-landing-zone-example"`,
	} {
		if !strings.Contains(p, want) {
			t.Errorf("broad-PAT env patch missing %q:\n%s", want, p)
		}
	}
	// The placeholders the base ships must not survive a real render.
	if strings.Contains(p, "REPLACE_ME") {
		t.Errorf("rendered patch still carries REPLACE_ME:\n%s", p)
	}
}
func TestComponentRegistry_AplCoreMapping(t *testing.T) {
	// The unified model routes some components to the apl-core (values.yaml) backend.
	obs, ok := LookupComponent("observability")
	if !ok {
		t.Fatal("observability component missing")
	}
	for _, app := range []string{"prometheus", "loki", "grafana"} {
		found := false
		for _, a := range obs.AplCoreApps {
			if a == app {
				found = true
			}
		}
		if !found {
			t.Errorf("observability should map to apl-core app %q (got %v)", app, obs.AplCoreApps)
		}
	}
	// harbor spans BOTH backends.
	h, _ := LookupComponent("harbor")
	if len(h.AplCoreApps) == 0 || len(h.ManifestResources) == 0 {
		t.Errorf("harbor should use both backends; got aplCore=%v manifest=%v", h.AplCoreApps, h.ManifestResources)
	}
	// ComponentEnabled returns false for an unknown component and honors a partial map.
	if ComponentEnabled(map[string]ComponentToggle{}, "nonexistent") {
		t.Error("an unknown component → not enabled")
	}
	if !ComponentEnabled(map[string]ComponentToggle{}, "openbao") {
		t.Error("openbao defaults enabled")
	}
}
