package clusterspec

import "strings"

// kustomize.go renders the two committed-but-derived kustomizations under
// apl-values/<env>/manifest/ from a deployment's enabled components (the
// llz-first-party / Argo backend):
//
//   - kustomization.yaml        — the parent tree apl-operator's Argo CD syncs;
//     its resources: list selects which raw manifests + the argocd/ subdir apply,
//     plus any patches the components bring.
//   - argocd/kustomization.yaml — the AppProject + the wave-ordered component
//     Applications.
//
// These are the ONLY apl-values files the spec commits (the rest of the per-env
// overlay is cloned from example, the tfvars are transient, and apl-core app
// toggles patch values.yaml): in-cluster Argo CD syncs committed git, so the
// component selection cannot be a working-tree-only render. They carry a generated
// header and are verified against the spec by `llz render --check`. Output is
// deterministic (registry order) so the check is stable and diffs stay localized.

const genHeader = `# GENERATED by ` + "`llz render`" + ` from the LandingZone spec — DO NOT EDIT.
# Toggle components via spec.components in environments/<env>.yaml, then re-run
# ` + "`llz render`" + `. See docs/landing-zone-spec.md.
`

const kustomizePreamble = genHeader + `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
`

// RenderManifestKustomization returns the parent manifest kustomization.yaml for
// the given component toggles: the resources: contributed by each enabled
// component (in registry order) plus any patches they bring.
func RenderManifestKustomization(components map[string]ComponentToggle) string {
	var resources []string
	var patches []Patch
	for _, c := range Components {
		if !ComponentEnabled(components, c.Name) {
			continue
		}
		resources = append(resources, c.ManifestResources...)
		patches = append(patches, c.Patches...)
	}

	var b strings.Builder
	b.WriteString(kustomizePreamble)
	b.WriteString("\nresources:\n")
	for _, res := range resources {
		b.WriteString("  - " + res + "\n")
	}
	if len(patches) > 0 {
		b.WriteString("\npatches:\n")
		for _, p := range patches {
			b.WriteString("  - path: " + p.Path + "\n")
			b.WriteString("    target:\n")
			b.WriteString("      group: " + p.Group + "\n")
			b.WriteString("      version: " + p.Version + "\n")
			b.WriteString("      kind: " + p.Kind + "\n")
			b.WriteString("      name: " + p.Name + "\n")
		}
	}
	return b.String()
}

// RenderArgoKustomization returns argocd/kustomization.yaml: the wave-ordered
// AppProject + component Applications contributed by each enabled component.
func RenderArgoKustomization(components map[string]ComponentToggle) string {
	var resources []string
	for _, c := range Components {
		if !ComponentEnabled(components, c.Name) {
			continue
		}
		resources = append(resources, c.ArgoApps...)
	}

	var b strings.Builder
	b.WriteString(kustomizePreamble)
	b.WriteString("\nresources:\n")
	for _, res := range resources {
		b.WriteString("  - " + res + "\n")
	}
	return b.String()
}
