package clusterspec

import (
	"strings"
	"testing"
)

// allOn is the default component set (every component enabled except DefaultDisabled).
func allOn() map[string]ComponentToggle {
	m := map[string]ComponentToggle{}
	for _, c := range Components {
		m[c.Name] = ComponentToggle{Enabled: boolPtr(!c.DefaultDisabled)}
	}
	return m
}

func TestRenderManifestKustomization(t *testing.T) {
	out := RenderManifestKustomization(allOn(), "", "")
	// Thin overlay: the shared base + a health-inert Application CR under resources:
	// for each enabled CARVED component (blast-radius decomposition) + a components:
	// list of the remaining plain component dirs.
	for _, want := range []string{
		"GENERATED by", "kind: Kustomization",
		"- ../../_shared/manifest",
		// carved components → App CRs under resources:, NOT components: dirs
		"- llz-externalsecrets.yaml",
		"- llz-observability.yaml",
		"- llz-harbor.yaml",
		"- llz-reconciler.yaml",
		// plain (non-carved) components stay as components: dirs
		"- ../../components/openbao",
		"- ../../components/certManager",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("thin overlay missing %q:\n%s", want, out)
		}
	}
	// Carved components no longer appear as components: dirs, and their per-env
	// patches move into their own App source root — so the manifest overlay carries
	// NO patches: section (every patch-bearing component is carved).
	for _, absent := range []string{
		"- ../../components/externalSecrets",
		"- ../../components/observability",
		"- ../../components/harbor",
		"- ../../components/llzReconciler",
		"patches:", "llz-reconciler-env-patch.yaml",
	} {
		if strings.Contains(out, absent) {
			t.Errorf("carved component leaked %q into the manifest overlay:\n%s", absent, out)
		}
	}
	// Mandatory components (argocd, clusterFoundation) live in the base — never in
	// the components: list.
	if strings.Contains(out, "components/argocd") || strings.Contains(out, "components/clusterFoundation") {
		t.Errorf("mandatory components must not be listed (they're in the base):\n%s", out)
	}
	// Disabling harbor drops its carved App CR (and only it).
	off := allOn()
	off["harbor"] = ComponentToggle{Enabled: boolPtr(false)}
	dropped := RenderManifestKustomization(off, "", "")
	if strings.Contains(dropped, "llz-harbor.yaml") {
		t.Error("disabled harbor should drop its carved App CR")
	}
	if !strings.Contains(dropped, "llz-observability.yaml") {
		t.Error("disabling harbor must not drop sibling carved Apps")
	}
}

func TestRenderManifestKustomization_RemoteRefs(t *testing.T) {
	const ref = "v9.9.9"
	out := RenderManifestKustomization(allOn(), ref, "")
	// Token-free plain components are fetched from the template repo at the pinned ref.
	for _, want := range []string{
		"- github.com/akamai-consulting/lke-landing-zone//instance-template/apl-values/components/openbao?ref=v9.9.9",
		"- github.com/akamai-consulting/lke-landing-zone//instance-template/apl-values/components/certManager?ref=v9.9.9",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("remote ref missing %q:\n%s", want, out)
		}
	}
	// The shared _shared/manifest base is fetched remotely too (Phase 1); its per-
	// instance instance-custom Application is split OUT and stays a local resource.
	if !strings.Contains(out, "- github.com/akamai-consulting/lke-landing-zone//instance-template/apl-values/_shared/manifest?ref=v9.9.9") {
		t.Errorf("shared base should be a remote ref:\n%s", out)
	}
	if !strings.Contains(out, "- instance-custom.yaml") {
		t.Errorf("instance-custom App must stay a local resource:\n%s", out)
	}
	// An empty ref keeps everything local (drift-check default / no instance context).
	local := RenderManifestKustomization(allOn(), "", "")
	if strings.Contains(local, "github.com/akamai-consulting") {
		t.Errorf("empty ref must stay fully local:\n%s", local)
	}
	if !strings.Contains(local, "- ../../_shared/manifest") || !strings.Contains(local, "- ../../components/openbao") {
		t.Errorf("empty ref should reference the base + components locally:\n%s", local)
	}
	// spec.dns.acmeEmail set → an inline ClusterIssuer patch carries the contact
	// (the shared dns tree ships email: "" and is now remote, so it can't be rewritten).
	withEmail := RenderManifestKustomization(allOn(), ref, "ops@example.com")
	for _, want := range []string{"kind: ClusterIssuer", "path: /spec/acme/email", "value: ops@example.com"} {
		if !strings.Contains(withEmail, want) {
			t.Errorf("acmeEmail patch missing %q:\n%s", want, withEmail)
		}
	}
	if strings.Contains(out, "/spec/acme/email") {
		t.Errorf("unset acmeEmail must emit no ClusterIssuer patch:\n%s", out)
	}
}

func TestRenderCarvedAppKustomization_RemoteRefs(t *testing.T) {
	const ref = "v9.9.9"
	// A token-free carved component (observability) is fetched remotely at the ref.
	obs, _ := LookupComponent("observability")
	if got := RenderCarvedAppKustomization(obs, ref, ""); !strings.Contains(got,
		"- github.com/akamai-consulting/lke-landing-zone//instance-template/apl-values/components/observability?ref=v9.9.9") {
		t.Errorf("observability carved kustomization should reference the remote ref:\n%s", got)
	}
	// llzReconciler is remote (Phase 0 moved its image to an images: transformer), and
	// with an imageTag set the carved kustomization retags the shared :latest image.
	rec, _ := LookupComponent("llzReconciler")
	got := RenderCarvedAppKustomization(rec, ref, "sha-abc123")
	if !strings.Contains(got, "components/llzReconciler?ref=v9.9.9") {
		t.Errorf("llzReconciler should be a remote ref now:\n%s", got)
	}
	for _, want := range []string{"images:", "name: ghcr.io/akamai-consulting/llz", "newTag: sha-abc123"} {
		if !strings.Contains(got, want) {
			t.Errorf("llzReconciler carved kustomization missing image retag %q:\n%s", want, got)
		}
	}
	// clusterHealthWorkflow's image is in an Argo WorkflowTemplate (a CRD the images:
	// transformer can't reach), so it stays a LOCAL component with no images: block.
	chw, _ := LookupComponent("clusterHealthWorkflow")
	chwK := RenderCarvedAppKustomization(chw, ref, "sha-abc123")
	if !strings.Contains(chwK, "- ../../../components/clusterHealthWorkflow") {
		t.Errorf("clusterHealthWorkflow must stay a local reference:\n%s", chwK)
	}
	if strings.Contains(chwK, "github.com/akamai-consulting") || strings.Contains(chwK, "images:") {
		t.Errorf("clusterHealthWorkflow must be local with no images: transformer:\n%s", chwK)
	}
	// A component that doesn't run the llz image (observability) gets no images: block.
	if strings.Contains(RenderCarvedAppKustomization(obs, ref, "sha-abc123"), "images:") {
		t.Errorf("observability should not get an llz images: transformer")
	}
}

func TestRenderCarvedApp(t *testing.T) {
	es, _ := LookupComponent("externalSecrets")
	app := RenderCarvedApp(es, "prod", "https://github.com/acme/inst.git", "v1.2.3")
	for _, want := range []string{
		"kind: Application",
		"name: llz-externalsecrets",
		"project: platform-bootstrap",
		`argocd.argoproj.io/sync-wave: "-10"`, // externalSecrets is the dependency root → lowest
		"repoURL: https://github.com/acme/inst.git",
		"targetRevision: v1.2.3",
		"path: apl-values/prod/apps/externalSecrets",
		"namespace: external-secrets",
		"SkipDryRunOnMissingResource=true",
	} {
		if !strings.Contains(app, want) {
			t.Errorf("carved App CR missing %q:\n%s", want, app)
		}
	}
	// externalSecrets (dependency root) must carry a strictly lower App wave than
	// every consumer App — the ordering the wave-dependency-guard enforces.
	esWave := es.CarvedApp.AppWave
	for _, name := range []string{"observability", "harbor", "llzReconciler"} {
		c, _ := LookupComponent(name)
		if c.CarvedApp == nil {
			t.Fatalf("%s should be carved", name)
		}
		if esWave >= c.CarvedApp.AppWave {
			t.Errorf("externalSecrets App wave %d must be < %s App wave %d", esWave, name, c.CarvedApp.AppWave)
		}
	}
}

func TestRenderCarvedAppKustomization(t *testing.T) {
	// A carved component WITH a patch (observability) references the shared Component
	// three levels up + its env patch.
	obs, _ := LookupComponent("observability")
	k := RenderCarvedAppKustomization(obs, "", "")
	for _, want := range []string{
		"kind: Kustomization",
		"- ../../../components/observability",
		"patches:",
		"path: otel-collector-tls-san-patch.yaml",
		"kind: Certificate",
	} {
		if !strings.Contains(k, want) {
			t.Errorf("carved App kustomization missing %q:\n%s", want, k)
		}
	}
	// A carved component WITHOUT a patch (externalSecrets) omits the patches: section.
	es, _ := LookupComponent("externalSecrets")
	if got := RenderCarvedAppKustomization(es, "", ""); strings.Contains(got, "patches:") {
		t.Errorf("patch-less carved component should omit patches::\n%s", got)
	}
}

func TestSetACMEEmail(t *testing.T) {
	// Two ClusterIssuers (production + staging), each with an acme email line.
	base := `spec:
  acme:
    email: REPLACE_PER_ENV   # e.g. ops@example.com
---
spec:
  acme:
    email: REPLACE_PER_ENV   # e.g. ops@example.com
`
	got := SetACMEEmail(base, "ops@example.com")
	if strings.Contains(got, "REPLACE_PER_ENV") {
		t.Errorf("placeholder survived:\n%s", got)
	}
	if n := strings.Count(got, "email: ops@example.com"); n != 2 {
		t.Errorf("both issuer emails should be set, got %d:\n%s", n, got)
	}
	// Idempotent: re-rendering the already-filled content is a no-op.
	if again := SetACMEEmail(got, "ops@example.com"); again != got {
		t.Errorf("SetACMEEmail not idempotent:\n%s", again)
	}
	// Change-safe: a new email rewrites the existing value (not just the placeholder).
	changed := SetACMEEmail(got, "sre@example.com")
	if strings.Count(changed, "email: sre@example.com") != 2 || strings.Contains(changed, "ops@example.com") {
		t.Errorf("email change not applied:\n%s", changed)
	}
	// Unset (empty) email renders a valid `email: ""`, NOT the unparseable
	// placeholder — the ACME contact is optional, and shipping REPLACE_PER_ENV made
	// Let's Encrypt reject account registration (invalidContact).
	empty := SetACMEEmail(base, "")
	if strings.Contains(empty, "REPLACE_PER_ENV") {
		t.Errorf("empty email must strip the placeholder:\n%s", empty)
	}
	if n := strings.Count(empty, `email: ""`); n != 2 {
		t.Errorf("empty email should render `email: \"\"` on both issuers, got %d:\n%s", n, empty)
	}
	// Idempotent on the empty rendering too.
	if again := SetACMEEmail(empty, ""); again != empty {
		t.Errorf("SetACMEEmail(empty) not idempotent:\n%s", again)
	}
}

func TestComponentRegistry_AplCoreMapping(t *testing.T) {
	// The unified model routes some components to the apl-core (values.yaml) backend.
	obs, ok := LookupComponent("observability")
	if !ok {
		t.Fatal("observability component missing")
	}
	for _, app := range []string{"prometheus", "loki", "grafana"} {
		found := false
		for _, a := range obs.AplCoreApps {
			if a == app {
				found = true
			}
		}
		if !found {
			t.Errorf("observability should map to apl-core app %q (got %v)", app, obs.AplCoreApps)
		}
	}
	// harbor spans BOTH backends.
	h, _ := LookupComponent("harbor")
	if len(h.AplCoreApps) == 0 || len(h.ManifestResources) == 0 {
		t.Errorf("harbor should use both backends; got aplCore=%v manifest=%v", h.AplCoreApps, h.ManifestResources)
	}
	// ComponentEnabled returns false for an unknown component and honors a partial map.
	if ComponentEnabled(map[string]ComponentToggle{}, "nonexistent") {
		t.Error("an unknown component → not enabled")
	}
	if !ComponentEnabled(map[string]ComponentToggle{}, "openbao") {
		t.Error("openbao defaults enabled")
	}
}
