package assertplatform

// ci_assert_instance_custom.go implements `llz ci assert-instance-custom` — the e2e
// gate that proves the operator escape hatch actually WORKS end to end, not merely
// that it renders and passes the static custom_layout checks.
//
// The release-e2e instantiate step seeds a trivial manifest under
// kubernetes-custom/namespaces/<ns>/ before it pushes the instance repo. On a
// converged cluster the instance-custom ApplicationSet's git directory generator must
// then have: discovered that directory, generated the Application
// instance-custom-<ns>, created namespace <ns> (CreateNamespace=true), and synced the
// seeded manifest into it. This asserts that generated Application EXISTS and reaches
// Synced + Healthy — a generation error (an invalid directory name, an unreachable
// repo) or a sync failure reds the e2e instead of shipping a silently-broken hatch.
//
// Why converge / assert-loki do NOT cover this: those gate the PLATFORM Applications.
// An escape hatch that generated nothing (the directory generator matched no path) or
// whose generated App never synced leaves every platform app color.Green — the
// instance-custom-<ns> App simply would not exist. Only an assertion that NAMES the
// generated App catches that. Its ROOT-CAUSE surface differs too: the parent here is
// the instance-custom ApplicationSet (whose health.lua reports ErrorOccurred on a
// generation fault), not platform-bootstrap's operationState — so this carries its own
// diagnostics rather than reusing assert-argo-app's app-of-apps ones.
//
// Read-only; drives the ambient KUBECONFIG through the aplGateDeps seam, so the
// deadline loop is unit-testable without a cluster.

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/akamai-consulting/lke-landing-zone/tools/internal/shared/cigate"
)

// assertInstanceCustom polls (10s cadence, immediate first probe) first until the
// generated Application exists, then until it is Synced + Healthy, both bounded by a
// single `within` deadline. Gating on BOTH Sync==Synced and Health==Healthy matters
// for the trivial-ConfigMap seed: a ConfigMap is health-inert, so a freshly-generated
// App can read Health=Healthy while still Sync=OutOfSync (not yet applied) — requiring
// Synced is what proves the manifest actually landed.
func assertInstanceCustom(d cigate.Deps, namespace, appSet string, within time.Duration) error {
	app := "instance-custom-" + namespace
	deadline := d.Now().Add(within)

	// Phase 1: the ApplicationSet git generator must have generated the App.
	for {
		if _, ok := d.Kubectl("-n", "argocd", "get", "application.argoproj.io", app); ok {
			break
		}
		if !d.Now().Before(deadline) {
			fmt.Fprintf(os.Stderr, "::error::Application %s never appeared within %s — the %s ApplicationSet did not generate it from kubernetes-custom/namespaces/%s/. %s\n",
				app, within, appSet, namespace, appSetDiag(d, appSet))
			return fmt.Errorf("%s not generated within %s", app, within)
		}
		fmt.Printf("waiting for %s to be generated by the %s ApplicationSet…\n", app, appSet)
		d.Sleep(10 * time.Second)
	}
	fmt.Printf("Application %s exists — waiting for Synced + Healthy…\n", app)

	// Phase 2: the generated App must sync the seeded manifest and go Healthy.
	for {
		sync, health := argoSyncHealth(d, "argocd", app)
		if sync == "Synced" && health == "Healthy" {
			fmt.Printf("OK: %s sync=%s health=%s — the escape hatch synced the seeded manifest into namespace %s.\n",
				app, sync, health, namespace)
			return nil
		}
		if !d.Now().Before(deadline) {
			fmt.Fprintf(os.Stderr, "::error::%s did not reach Synced+Healthy within %s (sync=%s health=%s). %s\n",
				app, within, sync, health, argoAppDiag(d, "argocd", app))
			return fmt.Errorf("%s not Synced+Healthy within %s (sync=%s health=%s)", app, within, sync, health)
		}
		fmt.Printf("  %s sync=%s health=%s — retrying…\n", app, sync, health)
		d.Sleep(10 * time.Second)
	}
}

// argoSyncHealth returns the Application's sync and health status ("" when the app is
// unreadable — e.g. it was deleted mid-poll, which the deadline path surfaces). Reads
// the object as JSON and parses the two fields — simpler and less fragile than a
// tab-delimited `-o jsonpath` shape, and the same read `llz ci converge` uses.
func argoSyncHealth(d cigate.Deps, namespace, app string) (sync, health string) {
	out, ok := d.Kubectl("-n", namespace, "get", "application.argoproj.io", app, "-o", "json")
	if !ok {
		return "", ""
	}
	// The seam folds stderr into out; skip any leading noise before the JSON body.
	if i := strings.IndexByte(out, '{'); i > 0 {
		out = out[i:]
	}
	var a struct {
		Status struct {
			Sync   struct{ Status string } `json:"sync"`
			Health struct{ Status string } `json:"health"`
		} `json:"status"`
	}
	if json.Unmarshal([]byte(out), &a) != nil {
		return "", ""
	}
	return a.Status.Sync.Status, a.Status.Health.Status
}

// appSetDiag summarizes the ApplicationSet's status conditions — a generation /
// validation error (ErrorOccurred: an invalid generated App, an unreachable repo)
// surfaces there and explains a generated App that never appeared. Best-effort:
// returns a hint when the ApplicationSet is unreadable.
func appSetDiag(d cigate.Deps, appSet string) string {
	out, ok := d.Kubectl("-n", "argocd", "get", "applicationset", appSet,
		"-o", `jsonpath={range .status.conditions[*]}[{.type}: {.status} {.message}]{end}`)
	if out = strings.TrimSpace(out); !ok || out == "" {
		return fmt.Sprintf("%s ApplicationSet state unavailable (missing, or cluster unreachable)", appSet)
	}
	return fmt.Sprintf("%s conditions: %s", appSet, out)
}

// argoAppDiag returns a one-line sync/health/conditions/operationState summary of the
// generated Application for the deadline failure annotation. Best-effort.
func argoAppDiag(d cigate.Deps, namespace, app string) string {
	out, ok := d.Kubectl("-n", namespace, "get", "application.argoproj.io", app,
		"-o", `jsonpath={.status.sync.status}/{.status.health.status}{range .status.conditions[*]} [{.type}: {.message}]{end} op={.status.operationState.message}`)
	if out = strings.TrimSpace(out); !ok || out == "" {
		return fmt.Sprintf("%s state unavailable", app)
	}
	return fmt.Sprintf("%s sync/health/conditions: %s", app, out)
}
